### ISSUE TITLE
Shade control slider causes issues on shades that can only open and close

### ISSUE THREAD

**Issue by rwgunther** [aarons22/homebridge-bond#100]
With support for shades now available, HomeKit apps show shades as a slider, which can be adjusted up and down. Currently, though, shades can only be opened and closed—and even as you enhance shade support, Bond still only offers open/close/stop for some shades. The problem now is that if you adjust the slider, it can cause problems for the shades, sending multiple open/close commands.

It would be nice for the control for shades with only open/close support to snap to either the open or closed position.

**Comment by aarons22** [comment]
Thanks for opening the issue! This has been fixed in [2.8.2](https://github.com/aarons22/homebridge-bond/releases/tag/2.8.2)
