### ISSUE TITLE
2.8.9 on hoobs does not load bond accessories

### ISSUE THREAD

**Issue by cleanev** [aarons22/homebridge-bond#101]
**Describe the bug**
Plug-in version 2.8.9 does not load any bond accessories, throws errors

**Expected behavior**
Bond accessories loaded on prior version and worked well

**Information (please complete the following information):**
 - Plugin version (run `npm list -g homebridge-bond` in terminal)
 - Bond firmware version - 2.14.5
 - iOS version (if issue is related to Home app) - N/A

**Additional context**
Log snippet
9/2/2020, 12:29:51 PM Bridge is running on port 51826.
9/2/2020, 12:29:51 PM [Bond] 5 cached accessories were loaded
9/2/2020, 12:29:51 PM [Bond] Getting devices for this Bond (ZZCJnnnnn)...
9/2/2020, 12:29:51 PM [Bond] 5 devices were found on this Bond (ZZCJnnnnn).
9/2/2020, 12:29:51 PM [Bond] No new devices to add for this Bond (ZZCJnnnnn).
9/2/2020, 12:29:51 PM [Bond] Configuring Accessory: B
9/2/2020, 12:29:51 PM [Bond] No Bond found for Device: B.
          This Device may have been removed from your Bond but still exists in cachedAccessories.
9/2/2020, 12:29:51 PM [Bond] Configuring Accessory: C
9/2/2020, 12:29:51 PM [Bond] No Bond found for Device: C.
          This Device may have been removed from your Bond but still exists in cachedAccessories.
9/2/2020, 12:29:51 PM [Bond] Configuring Accessory: A
9/2/2020, 12:29:51 PM [Bond] No Bond found for Device: A.
          This Device may have been removed from your Bond but still exists in cachedAccessories.
9/2/2020, 12:29:51 PM [Bond] Configuring Accessory: D
9/2/2020, 12:29:51 PM [Bond] No Bond found for Device: D.
          This Device may have been removed from your Bond but still exists in cachedAccessories.
9/2/2020, 12:29:51 PM [Bond] Configuring Accessory: O
9/2/2020, 12:29:51 PM [Bond] No Bond found for Device: O.
          This Device may have been removed from your Bond but still exists in cachedAccessories.

**Comment by aarons22** [comment]
Thanks for letting me know. Can you provide logs in [debug mode](https://github.com/aarons22/homebridge-bond/wiki/Enabling-Debug-Mode)? That helps me more easily identify issues.

**Comment by cleanev** [comment]
Hello @aarons22 - 
I ended up trying these steps to get it to work
1. stop hoobs from webadmin gui
2. Rename /home/hoobs/.hoobs/etc/accessories/cachedAccessories to cachedAccessoriedOLD
Above did NOT work as new file is exactly the same size as old one

Checked /home/hoobs/.hoobs/etc/persist folder
1. Rename AccessoryInfo.MACADDR.json to OLD
2. Rename IdentifierCache.MACADDR.json to OLD
3. start hoobs service from webgui
4. new files created that are smaller
5. Homekit lost track of hoobs bridge
6. Reset hoobs and from configuration option 'help' 
7. setup HomeKit again

Next time I will make sure I provide logs with 'hoobs -d' so you can parse thru the issue.

**Comment by aarons22** [comment]
Thanks @cleanev - sounds like something went wrong with some data migration. Going to look into it this weekend.

**Comment by aarons22** [comment]
oh wait I'm re-reading your steps. so you are no longer having an issue?
