### ISSUE TITLE
Bond stopped responding with latest update.

### ISSUE THREAD

**Issue by sebastiangoldstein** [aarons22/homebridge-bond#102]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Information (please complete the following information):**
 - Plugin version (run `npm list -g homebridge-bond` in terminal)
 - Bond firmware version
 - iOS version (if issue is related to Home app)

**Additional context**

**Comment by sebastiangoldstein** [comment]
Describe the bug
BOND stopped responding to HOOBS after a recent update.

Expected behavior
Lights and fands no longer responding

Screenshots
If applicable, add screenshots to help explain your problem.

Information (please complete the following information):

Plugin version (run npm list -g homebridge-bond in terminal)
Up to Date
Bond
HOOBS Certified
2.8.9 published 8/31/2020 • 1 day ago

Bond firmware version
2.26.1

iOS version (if issue is related to Home app)
14 Beta 5

Additional context
Add any other context about the problem here.

**Comment by aarons22** [comment]
Thanks for letting me know. Can you provide logs in [debug mode](https://github.com/aarons22/homebridge-bond/wiki/Enabling-Debug-Mode)? That helps me more easily identify issues.

**Comment by sebastiangoldstein** [comment]
Not really sure how to do that - I'm a relative NOOB at HOOBS.
However, all was working fine with the plugin for months before I updated (I think yesterday).
Since then, Apple Home app makes it look like its working but no effect on the Bond controlled fans. 
Going through the Bond App still works fine.
I just tried to turn on a fanlight and a fan - this is what the log says.

9/2/2020, 11:06:46 PM NOTICE: Sending Device Command: on | Name: (Loft Lamp) | DeviceID: (f60d157c-cba8-4574-875c-ebf5b34f6332) | SendToLocalHub: (false)
9/2/2020, 11:06:47 PM NOTICE: Sending Device Command: setLevel | Value: {"value1":100} | Name: (Loft Lamp) | DeviceID: (f60d157c-cba8-4574-875c-ebf5b34f6332) | SendToLocalHub: (false)
9/2/2020, 11:06:49 PM NOTICE: Sending Device Command: off | Name: (Loft Lamp) | DeviceID: (f60d157c-cba8-4574-875c-ebf5b34f6332) | SendToLocalHub: (false)
9/2/2020, 11:06:49 PM INFO: [Device Event]: (Loft Lamp) [SWITCH] is off
9/2/2020, 11:06:50 PM NOTICE: Sending Device Command: on | Name: (Loft Lamp) | DeviceID: (f60d157c-cba8-4574-875c-ebf5b34f6332) | SendToLocalHub: (false)
9/2/2020, 11:06:51 PM INFO: [Device Event]: (Loft Lamp) [SWITCH] is on
9/2/2020, 11:06:51 PM NOTICE: Sending Device Command: setLevel | Value: {"value1":100} | Name: (Loft Lamp) | DeviceID: (f60d157c-cba8-4574-875c-ebf5b34f6332) | SendToLocalHub: (false)
9/2/2020, 11:06:52 PM INFO: [Device Event]: (Loft Lamp) [LEVEL] is 100
9/2/2020, 11:06:54 PM NOTICE: Sending Device Command: off | Name: (Loft Lamp) | DeviceID: (f60d157c-cba8-4574-875c-ebf5b34f6332) | SendToLocalHub: (false)
9/2/2020, 11:06:54 PM INFO: [Device Event]: (Loft Lamp) [SWITCH] is off

let me know what else I can send you.

**Comment by mdombrowski13** [comment]
Same problem.  

Homebridge 1.1.3
Homebridge Bond 2.8.9

As soon as I upgraded to v2.8.9 bond accessories no longer work in homebridge/homekit.

**Comment by aarons22** [comment]
Thanks all - sounds like something went wrong with some data migration. Going to look into it this weekend.

**Comment by aarons22** [comment]
@mdombrowski13 @sebastiangoldstein Can you Uninstall and reinstall the bond plugin? I know that isn't ideal if you have Scenes associated with your devices, but I had to make a breaking change in how I handle devices and the data migration I attempted apparently didn't work well for everyone. I promise this isn't something I would do if I didn't have to!

**Comment by mdombrowski13** [comment]
@aarons22 i’ll try to test it out this weekend.  I did try a roll back to 2.8.7 and its working flawlessly again.

**Comment by aarons22** [comment]
@mdombrowski13 if you are able to run your setup in debug mode (instructions [here](https://github.com/aarons22/homebridge-bond/wiki/Enabling-Debug-Mode)) and provide your logs, that would be very helpful!

**Comment by sebastiangoldstein** [comment]
@aarons22, not sure if I'm running in debug or not, however, I think this is interesting...
Even though BOND app works fine HOOBS log shows this at startup:
my log show this at startup:

9/4/2020, 10:11:18 PM [Bond] 4 cached accessories were loaded
9/4/2020, 10:11:18 PM [Bond] Getting devices for this Bond (AJ14670)...
9/4/2020, 10:11:18 PM [Bond] 4 devices were found on this Bond (AJ14670).
9/4/2020, 10:11:18 PM [Bond] No new devices to add for this Bond (AJ14670).
9/4/2020, 10:11:18 PM [Bond] Configuring Accessory: Loft Loft
9/4/2020, 10:11:18 PM [Bond] No Bond found for Device: Loft.
          This Device may have been removed from your Bond but still exists in cachedAccessories.
9/4/2020, 10:11:18 PM [Bond] Configuring Accessory: Guest Bedroom Guest Bedroom
9/4/2020, 10:11:18 PM [Bond] No Bond found for Device: Guest Bedroom.
          This Device may have been removed from your Bond but still exists in cachedAccessories.
9/4/2020, 10:11:18 PM [Bond] Configuring Accessory: Playroom Playroom
9/4/2020, 10:11:18 PM [Bond] No Bond found for Device: Playroom.
          This Device may have been removed from your Bond but still exists in cachedAccessories.
9/4/2020, 10:11:18 PM [Bond] Configuring Accessory: Master Bedroom Master Bedroom
9/4/2020, 10:11:18 PM [Bond] No Bond found for Device: Master Bedroom.
          This Device may have been removed from your Bond but still exists in cachedAccessories.

**Comment by sebastiangoldstein** [comment]
@aarons22,
I followed your suggestion above and uninstalled then reinstalled the HOOBS BOND Plugin.
That seemed to do the trick!
Found all 4 fans and added them to the default room in Apple Home.
Will rebuild Automations.
Thanks!

P9/4/2020, 10:25:54 PM [Bond] 0 cached accessories were loaded
9/4/2020, 10:25:54 PM [Bond] Getting devices for this Bond (AJ14670)...
9/4/2020, 10:25:54 PM [Bond] 4 devices were found on this Bond (AJ14670).
9/4/2020, 10:25:54 PM [Bond] Attempting to add 4 devices that were not previously added.
9/4/2020, 10:25:55 PM [Bond] Adding accessory Loft Loft
9/4/2020, 10:25:55 PM [Bond] Adding accessory Guest Bedroom Guest Bedroom
9/4/2020, 10:25:55 PM [Bond] Adding accessory Playroom Playroom
9/4/2020, 10:25:55 PM [Bond] Adding accessory Master Bedroom Master Bedroom

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by aarons22** [comment]
@mdombrowski13 can you stop posting 😬

**Comment by mdombrowski13** [comment]
@aarons22,

This did not solve it for me. I deleted all my bonds (2) and the 3 fans I have associated with it.  Started from scratch, deleted plug in and resinalled home bridge plug in from scratch.  even tried creating a new instance of homebringe just for the test.  Still nothing.  if i revert back to 2.8.7 they work instantly.

**Comment by mdombrowski13** [comment]
sorry no clue what happened!

**Comment by aarons22** [comment]
@mdombrowski13 a few questions:
- Would you mind providing your cachedAccessories file? 
- What is the firmware version of your Bonds? If they drastically out of date it's possible the API is too old for the new id system I recently added.
- If possible, can you provide logs (preferably while in [debug mode](https://github.com/aarons22/homebridge-bond/wiki/Enabling-Debug-Mode)).

**Comment by aarons22** [comment]
Closing this one since the OP's issue is resolved. Feel free to open a new issue with logs demonstrating the issue!
