### ISSUE TITLE
Plug-in on HOOBS?

### ISSUE THREAD

**Issue by rhuss2** [aarons22/homebridge-bond#106]
When will version 3.x show up in HOOBS? Currently I am still on version 2.x, and no upgrade is available.

**Comment by aarons22** [comment]
To be honest I'm not really sure how HOOBS updates plugins on their end. 

@hoobs-org any thoughts?

**Comment by rhuss2** [comment]
I contacted HOOB support they updated it last night.

**Comment by aarons22** [comment]
Great!
