### ISSUE TITLE
Use of Fan Speeds & Percentages

### ISSUE THREAD

**Issue by rhuss2** [aarons22/homebridge-bond#108]
If I change my plug-in to use Fan Speeds, will I have to change any existing automations to remove percentages, as they were setup with them? Or can automations use percentages or Fan Speeds?

**Comment by aarons22** [comment]
@rhuss2 great question. To be honest, I'm not sure, I don't do any automations and I don't use the Fan Speeds feature. My gut says it depends on the automation. 

Happy to continue the dialogue, but going to close this issue unless there is a specific issue with this feature.
