### ISSUE TITLE
Bond 3.0 stopped working with HOOBS 3.2.9

### ISSUE THREAD

**Issue by bjbires1248** [aarons22/homebridge-bond#109]
**Describe the bug**
The plugin will not identify bond products

**Information (please complete the following information):**
 - 3.0
 - 2.15.1
 - Hoobs
 
**Logs**
10/22/2020, 10:21:43 PM - [Bond] 0 cached accessories were loaded
10/22/2020, 10:21:43 PM - [Bond] Getting devices for this Bond (ZZBL50259)...
10/22/2020, 10:21:43 PM - [Bond] 6 devices were found on this Bond (ZZBL50259).
10/22/2020, 10:21:43 PM - [Bond] Attempting to add 6 devices that were not previously added.
10/22/2020, 10:22:16 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:16 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:16 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:16 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:16 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:16 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:17 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:17 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:17 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:17 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:17 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:17 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:17 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:17 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:17 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:17 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:17 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:17 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:18 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:18 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:18 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:18 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:19 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:20 PM - [Bond] A request error occurred: undefined
10/22/2020, 10:22:20 PM - [Bond] Error getting devices: TypeError: Cannot read property 'action' of undefined

I am really new to HOOBS and do not know how to do debug in HOOBS. This is what I see in the normal log.

**Comment by aarons22** [comment]
This is going to be tough without debug logs. Can you give me more info? Have you used this plugin on previous versions? What types of devices do you have in Bond?
