### ISSUE TITLE
All my lights have dimmer switches now

### ISSUE THREAD

**Issue by lherlitz** [aarons22/homebridge-bond#113]
None of my lights dim and they are all toggle switches in the bond app. But now in homebridge, all lights show as dimmable

**Comment by aarons22** [comment]
Sorry about that, it was a bug in 3.1.0. Should be fixed in [3.1.2](https://github.com/aarons22/homebridge-bond/releases/tag/3.1.2)

**Comment by lherlitz** [comment]
Yup! Fixed now. Thanks!
