### ISSUE TITLE
Support Bond  > Somfy shades "My" command

### ISSUE THREAD

**Issue by spikenheimer** [aarons22/homebridge-bond#118]
Somfy shades have a 3rd command in addition to "open" and "close" and that is the "my" command - this tells the shades to move to a preset position.  For example i have 2 shades that i can move to a 'middle' sequel position so i can block afternoon direct sun but still leave much of the window open and unblocked for viewing.

in other direct to somfy  bridge code (a smart things -> somfy z-wave <>RTS controller plugin for ST) they implemented the code such that any partial value setting of the shade percentage would just execute the Somfy "My" command and then set the internal tracker to 50% shade level.    ( reference cloned code here: https://github.com/spikenheimer/SmartThingsSomfy/blob/master/devicetypes/imnotbob/somfy-shades.src/somfy-shades.groovy )

in the bond app they have it implemented as a "My" button.  (see attached screenshot)
![image](https://user-images.githubusercontent.com/8379652/98740489-c4ccd680-2370-11eb-8bb1-702bcceb9412.png)

i did some digging and found that the command that works is "Preset" and programmatically i am able to execute this via curl with the following:
```
curl -X PUT  -d "{\"_token\": \" <mytoken>\"}" -i http://bond/v2/devices/<device_id>/actions/Preset
HTTP/1.1 200 OK
Content-Length: 18
Content-Type: application/json; charset=utf-8

{"_":"eed7380c"}

```

for more information this is what was returned for  the device itself:

```
curl -X GET  -d "{\"_token\": \" <mytoken>\"}" -i http://bond/v2/devices/<device_id>
HTTP/1.1 200 OK
Content-Length: 275
Content-Type: application/json; charset=utf-8

{"name":"LR Shade Left","type":"MS","location":"Living Room","template":"RMS12","actions":["Close","Open","Hold","Pair","Preset","Stop","ToggleOpen"],"_":"c9be25c5","commands":{"_":"a035c0eb"},"state":{"_":"cd53b897"},"properties":{"_":"4976a616"},"skeds":{"_":"1977f2ff"}}

```

i can submit further info as necessary.

thanks!

**Comment by aarons22** [comment]
@chrismerk any thoughts on this one? I'm not seeing `Preset` in the docs anywhere, so I'm hesitant to use it, but I am seeing references in the Bond forum.

**Comment by aarons22** [comment]
@spikenheimer I attempted this in [3.2.1](https://github.com/aarons22/homebridge-bond/releases/tag/3.2.1).

Please give it a try and report back 😄

**Comment by spikenheimer** [comment]
hehheh so i apparently hadn’t seen my notifying me about the change, and instead experienced it unknowingly this morning opening my bedroom shades... as in “uhhh why is there an extra power button on my shade control?”
that aside this feels like the best implementation possible currently given a lack of standardization on this type of “command” for shades/blinds in homekit.  

also huge thanks for giving it a try.  twas a very pleasant realization as to what had happened 😂 

-spike
