### ISSUE TITLE
Multiple Bonds

### ISSUE THREAD

**Issue by Webster83** [aarons22/homebridge-bond#119]
On Hoobs, I've been unable to add multiple bonds (have one Smart by Bond, which works sans dimming, and one Bond Bridge -- not working). 

When I update the config to add the second IP and token, and save the changes, the changes are immediately wiped and reverted.

**Comment by aarons22** [comment]
Honestly, this sounds like a @hoobs-org issue, but I'm happy to help. Can you provide more info? Maybe some screenshots of what's happening?

**Comment by aarons22** [comment]
Can you post your config as a screenshot from hoobs?
