### ISSUE TITLE
Only publish to HomeKit the controls configured in the Bond app.

### ISSUE THREAD

**Issue by Fernyman79** [aarons22/homebridge-bond#12]
In the Bond app, after configuring your fan, you can remove unnecessary/unwanted controls. In my case, I only need the Fan controls, since my fan lights are hard-wired to a switch in the wall.

The plugin, however, makes the deleted light controls available in HomeKit. Would be great to display the controls in the Home app exactly as they are in the Bond app.

**Comment by iRayanKhan** [comment]
Try Deleting the cache of the bond plugin

**Comment by plainsane** [comment]
> In the Bond app, after configuring your fan, you can remove unnecessary/unwanted controls. In my case, I only need the Fan controls, since my fan lights are hard-wired to a switch in the wall.
> 
> The plugin, however, makes the deleted light controls available in HomeKit. Would be great to display the controls in the Home app exactly as they are in the Bond app.

Yes, the code assumes you are enabling all that, I’ll try to swing around on it later...it’s going to be a forklift operation I feel.

**Comment by aarons22** [comment]
Closing this as it is no longer applicable with v2 API.
