### ISSUE TITLE
Shade control appears to be state dependent

### ISSUE THREAD

**Issue by rwgunther** [aarons22/homebridge-bond#121]
I have some shades I control with Bond that aren’t technically supported by Bond. Bond will control them, but not reliably. Oftentimes I need to send the same signal multiple times for it to “take.” This works when I use SmartThings or Alexa to control the blinds, but not with this plug-in. Somewhere in the stack of Bond, the plug-in, Homebridge, and HomeKit itself, it appears that bond commands only work if HomeKit reports the shades in question in the opposite state. E.g., If HomeKit reports the blinds as open, then Bond doesn’t send an Open signal.

I tried the “Include toggle switch” option, but that just appears to toggle the status of the blind in HomeKit. That’s not something that can be used for Automations, because there’s no way to know, programmatically, whether the shades and HomeKit status are out of sync. So I’m not clear what purpose that option actually serves. I think what’s really needed to solve this particular problem is a standard switch option for shades that lets you send consecutive open or close commands. Then if I press a button repeatedly to send an open command, it would presumably allow Bond to send multiple open signals.

Would it be possible to offer an option to represent shades as a standard switch?

**Comment by aarons22** [comment]
Hey @rwgunther  - honestly, I'd recommend you use [homebridge-blinds](https://github.com/dxdc/homebridge-blinds) if you want more state control with your blinds. He's done way more work fine-tuning shades operations, and I won't do much else on this plugin until the Bond API offers more. The best I can do is send open and close commands and read what state Bond thinks the shades are in.

One option with this plugin if you are just looking for a switch is the Generic device option.

**Comment by rwgunther** [comment]
OK, thanks. I'll look into that. Or I may just stick with SmartThings to automate my Bond-controlled devices. Bond's own SmartThings integration represents my shades as standard switches, allowing me to send open and close commands repeatedly that it honors, regardless of their current state.
