### ISSUE TITLE
Delay between multiple device commands

### ISSUE THREAD

**Issue by InstigatorX** [aarons22/homebridge-bond#143]
**Is your feature request related to a problem? Please describe.**
No problem per se, but when I have an automation that sends OFF to 2 devices on a single Bond, only 1 device reacts.

**Describe the solution you'd like**
I believe a delay should be introduced between successive commands sent to a Bond device to allow it time to send the command to 1st device. Saw a similar enh/fix for another device type that had same issue and gave me idea for this request. https://github.com/misenhower/homebridge-wyze-connected-home/pull/23/files

**Describe alternatives you've considered**
I could use a Shortcut with a WAIT, but that would unnecessarily complicate things.

**Additional context**
Thanks for this plugin...works great!

**Comment by aarons22** [comment]
I'd be really interested to see your logs when this happens, preferably in [debug mode](https://github.com/aarons22/homebridge-bond/wiki/Enabling-Debug-Mode) so I can see the requests and responses. If possible, would you be able to post a screen recoding of the automation in action as well? That might be helpful to see that in conjunction with the logs.

 I might be able to introduce a queue for a given bond to prevent more than one active request at a time.

**Comment by chrismerck** [comment]
The Bond Bridge internally has queueing for up to 32 transmissions. So, there shouldn't be a problem hitting the Bridge with a bunch of rapid-fire HTTP calls.

We did have problems with some ceiling fan receivers which required some silent period before the transmission addressed to them. Our fix was to add 350 ms of dead air between transmissions, only applying when controlling different devices on the same frequency +- 1 MHz. --- This fixed the problem for all known ceiling fan receivers.

However, if you're still facing this issue, please let our customer support know about it, so that we can eventually fix this at the firmware (radio driver or device template) level.

What kind of devices are you controlling?

**Comment by InstigatorX** [comment]
> The Bond Bridge internally has queueing for up to 32 transmissions. So, there shouldn't be a problem hitting the Bridge with a bunch of rapid-fire HTTP calls.
> 
> We did have problems with some ceiling fan receivers which required some silent period before the transmission addressed to them. Our fix was to add 350 ms of dead air between transmissions, only applying when controlling different devices on the same frequency +- 1 MHz. --- This fixed the problem for all known ceiling fan receivers.
> 
> However, if you're still facing this issue, please let our customer support know about it, so that we can eventually fix this at the firmware (radio driver or device template) level.
> 
> What kind of devices are you controlling?

Accent lighting. Simple on/off. I have a nightly "goodnight" scene in Homekit that turns off a bunch of lights. With the bond lights (2 of them) only 1 set gets turned off. Sometimes its the left, other times it's the right. Never both and happens 100% of the time. Could it be a Hoobs issue that too many commands are coming its way via the scene?

@aarons22 I'll enable debug so you can see what's happening.

**Comment by chrismerck** [comment]
Yeah, definitely check the logs from the Bond Bridge to see that it is really receiving both requests. If it _is_ receiving both requests, both should be transmitted with that ~350ms delay between. If that's not enough, maybe we can extend our signal API to specify a dead-time that must preceed the transmission, which would totally eliminate the need for larger sledgehammer delays in integrations such as this.

One useful tool might be our livelog feature, where you can get firmware logs streaming to your PC's terminal: https://github.com/bondhome/bond-cli

I frequently use this command in development: `python -m bond livelog --level debug`

**Comment by InstigatorX** [comment]
@chrismerck @aarons22 Here are the logs...

[Bond] Initializing Bond platform...
[Bond] Config: {
[Bond] Request (185e2c8522608000) [get http://192.168.86.242/v2/devices]
[Bond] Request (185e2c8522620000) [get http://192.168.86.242/v2/sys/version]
[Bond] Response (185e2c8522608000) [get http://192.168.86.242/v2/devices] - {"_":"229e3630","5183bc93":{"_":"376a927b"},"5fb9c82f":{"_":"988f8d3a"},"3142c837":{"_":"9f886363"},"61091e45":{"_":"e8ae609b"}}
[Bond] Response (185e2c8522620000) [get http://192.168.86.242/v2/sys/version] - {"target":"snowbird","fw_ver":"v2.17.4.2-beta","fw_date":"Tue Mar 23 15:57:59 UTC 2021","uptime_s":236880,"bondid":"BB16627","upgrade_http":true,"api":2,"_":"0663f1d3"}
[Bond] 
[Bond] 4 cached accessories were loaded
[Bond] Getting devices for this Bond (BB16627)...
[Bond] 4 devices were found on this Bond (BB16627).
[Bond] No new devices to add for this Bond (BB16627).
[Bond] UDP message sent to 192.168.86.242:30007
[Bond] Configuring Accessory: Family Room Alcove Left
[Bond] [Alcove Left] actions: TurnOff,TurnOn,Stop,TogglePower
[Bond] Request (185e2c8522c58000) [get http://192.168.86.242/v2/devices/5183bc93/state]
[Bond] Configuring Accessory: My Room Gate
[Bond] [Gate] actions: TogglePower,Stop,TurnOn,TurnOff
[Bond] Request (185e2c8522c70000) [get http://192.168.86.242/v2/devices/5fb9c82f/state]
[Bond] Configuring Accessory: Family Room Ceiling fan
[Bond] [Ceiling fan] actions: SetSpeed,OEMTimer,ToggleLight,OEMHomeAway,TurnOff,OEMRandom,OEMWalkAway,SetDirection,StartDimmer,Stop,TogglePower,TurnOn,IncreaseSpeed,DecreaseSpeed,ToggleDirection,TurnLightOn,TurnLightOff
[Bond] Request (185e2c8522ca8000) [get http://192.168.86.242/v2/devices/3142c837/state]
[Bond] Configuring Accessory: Family Room Alcove Right
[Bond] [Alcove Right] actions: TurnOff,TurnOn,Stop,TogglePower
[Bond] Request (185e2c8522cbc000) [get http://192.168.86.242/v2/devices/61091e45/state]
[Bond] Response (185e2c8522c58000) [get http://192.168.86.242/v2/devices/5183bc93/state] - {"power":0,"_":"7adae6d6"}
[Bond] Response (185e2c8522c70000) [get http://192.168.86.242/v2/devices/5fb9c82f/state] - {"power":0,"_":"723943e5"}
[Bond] Response (185e2c8522ca8000) [get http://192.168.86.242/v2/devices/3142c837/state] - {"power":0,"speed":1,"direction":-1,"light":0,"_":"8c07ce21"}
[Bond] Response (185e2c8522cbc000) [get http://192.168.86.242/v2/devices/61091e45/state] - {"power":0,"_":"59ff6ed7"}
[Bond] UDP Message received from 192.168.86.242:30007 - {"B":"BB16627"}
[Bond] Request (185e2c853ea40000) [put http://192.168.86.242/v2/devices/5183bc93/actions/TogglePower]
[Bond] Request (185e2c853ea6c000) [put http://192.168.86.242/v2/devices/61091e45/actions/TogglePower]
[Bond] UDP Message received from 192.168.86.242:30007 - {"B":"BB16627","t":"devices/5183bc93/state","i":"050000fad03b328b","f":100,"s":200,"m":0,"x":"bond","b":{"power":1,"_":"5ef1d5a6"}}
[Bond] [Alcove Left] Received new state: {"power":1,"_":"5ef1d5a6"}
[Bond] Response (185e2c853ea40000) [put http://192.168.86.242/v2/devices/5183bc93/actions/TogglePower] - {"_":"c4a6e7ff"}
[Bond] [Alcove Left] Toggled power: true
[Bond] UDP Message received from 192.168.86.242:30007 - {"B":"BB16627","t":"devices/61091e45/state","i":"050000f882699f22","f":100,"s":200,"m":0,"x":"bond","b":{"power":1,"_":"9f0327de"}}
[Bond] [Alcove Right] Received new state: {"power":1,"_":"9f0327de"}
[Bond] Response (185e2c853ea6c000) [put http://192.168.86.242/v2/devices/61091e45/actions/TogglePower] - {"_":"d5a65ddc"}
[Bond] [Alcove Right] Toggled power: true
[Bond] Request (185e2c854d080000) [put http://192.168.86.242/v2/devices/5183bc93/actions/TogglePower]
[Bond] Request (185e2c854d0b8000) [put http://192.168.86.242/v2/devices/61091e45/actions/TogglePower]
[Bond] UDP Message received from 192.168.86.242:30007 - {"B":"BB16627","t":"devices/5183bc93/state","i":"0500000d01285bf1","f":100,"s":200,"m":0,"x":"bond","b":{"power":0,"_":"7bfc25da"}}
[Bond] [Alcove Left] Received new state: {"power":0,"_":"7bfc25da"}
[Bond] Response (185e2c854d080000) [put http://192.168.86.242/v2/devices/5183bc93/actions/TogglePower] - {"_":"c4a6e7ff"}
[Bond] [Alcove Left] Toggled power: false
[Bond] UDP Message received from 192.168.86.242:30007 - {"B":"BB16627","t":"devices/61091e45/state","i":"0500000a51fa4857","f":100,"s":200,"m":0,"x":"bond","b":{"power":0,"_":"d9ed955e"}}
[Bond] [Alcove Right] Received new state: {"power":0,"_":"d9ed955e"}
[Bond] Response (185e2c854d0b8000) [put http://192.168.86.242/v2/devices/61091e45/actions/TogglePower] - {"_":"d5a65ddc"}
[Bond] [Alcove Right] Toggled power: false
[Bond] UDP message sent to 192.168.86.242:30007
[Bond] UDP Message received from 192.168.86.242:30007 - {"B":"BB16627"}

**Comment by aarons22** [comment]
Looking at the logs, everything seems to be functioning correctly.

Two simultaneous requests
```
[Bond] Request (185e2c853ea40000) [put http://192.168.86.242/v2/devices/5183bc93/actions/TogglePower]
[Bond] Request (185e2c853ea6c000) [put http://192.168.86.242/v2/devices/61091e45/actions/TogglePower]
```

The response logs are the same for any request:
- Raw UDP message (this ultimately drives the state of the Home app controls)
- parsed state from UDP message
- Response from request (indicates successful network request)
- Log from homebridge callback

 First request completes (`185e2c853ea40000`)
```
[Bond] UDP Message received from 192.168.86.242:30007 - {"B":"BB16627","t":"devices/5183bc93/state","i":"050000fad03b328b","f":100,"s":200,"m":0,"x":"bond","b":{"power":1,"":"5ef1d5a6"}}
[Bond] [Alcove Left] Received new state: {"power":1,"":"5ef1d5a6"}
[Bond] Response (185e2c853ea40000) [put http://192.168.86.242/v2/devices/5183bc93/actions/TogglePower] - {"":"c4a6e7ff"}
[Bond] [Alcove Left] Toggled power: true
```

Second request completes (`185e2c853ea6c000`)
```
[Bond] UDP Message received from 192.168.86.242:30007 - {"B":"BB16627","t":"devices/61091e45/state","i":"050000f882699f22","f":100,"s":200,"m":0,"x":"bond","b":{"power":1,"":"9f0327de"}}
[Bond] [Alcove Right] Received new state: {"power":1,"":"9f0327de"}
[Bond] Response (185e2c853ea6c000) [put http://192.168.86.242/v2/devices/61091e45/actions/TogglePower] - {"":"d5a65ddc"}
[Bond] [Alcove Right] Toggled power: true
```

And then again, but powering both devices off
```
[Bond] Request (185e2c854d080000) [put http://192.168.86.242/v2/devices/5183bc93/actions/TogglePower]
[Bond] Request (185e2c854d0b8000) [put http://192.168.86.242/v2/devices/61091e45/actions/TogglePower]
```

```
[Bond] UDP Message received from 192.168.86.242:30007 - {"B":"BB16627","t":"devices/5183bc93/state","i":"0500000d01285bf1","f":100,"s":200,"m":0,"x":"bond","b":{"power":0,"":"7bfc25da"}}
[Bond] [Alcove Left] Received new state: {"power":0,"":"7bfc25da"}
[Bond] Response (185e2c854d080000) [put http://192.168.86.242/v2/devices/5183bc93/actions/TogglePower] - {"":"c4a6e7ff"}
[Bond] [Alcove Left] Toggled power: false
```

```
[Bond] UDP Message received from 192.168.86.242:30007 - {"B":"BB16627","t":"devices/61091e45/state","i":"0500000a51fa4857","f":100,"s":200,"m":0,"x":"bond","b":{"power":0,"":"d9ed955e"}}
[Bond] [Alcove Right] Received new state: {"power":0,"":"d9ed955e"}
[Bond] Response (185e2c854d0b8000) [put http://192.168.86.242/v2/devices/61091e45/actions/TogglePower] - {"":"d5a65ddc"}
[Bond] [Alcove Right] Toggled power: false
```

I would recommend contacting Bond customer support as @chrismerck mentioned. As far as this plugin can tell, everything is functioning as expected.

**Comment by InstigatorX** [comment]
Instead of TogglePower, can you send discrete on/off? I don't have a toggle setup on the devices that aren't working. Also, I noticed toggle doesn't actually do anything for another device I have setup with a toggle.

**Comment by aarons22** [comment]
Based on the state activity I'm seeing, toggle is definitely doing _something_ on your Bond. If TogglePower wasn't working, the `power` value would never change. From my understanding, TogglePower is the same thing as TurnOff or TurnOn, but it's just based on the current state of the power (so if power is 1, it's the same as TurnOff, and vice versa). No discrete setup is required to enable toggle.

**Comment by aarons22** [comment]
The thread in this issue might be relevant to you: https://github.com/aarons22/homebridge-bond/issues/148

You can adjust the timing between commands, so maybe that would help?

**Comment by InstigatorX** [comment]
@aarons22 I set it to 10 reps and will see what happens as the automations run naturally throughout the day. Worked if I triggered them manually. Thx for pointer.

**Comment by InstigatorX** [comment]
@aarons22 seems to have worked. Thx!
