### ISSUE TITLE
Force fan state

### ISSUE THREAD

**Issue by searls** [aarons22/homebridge-bond#156]
I'm rocking 7 of [these fan remotes](https://www.homedepot.com/p/Home-Decorators-Collection-Kensgrove-72-in-LED-Indoor-Outdoor-Espresso-Bronze-Ceiling-Fan-with-Remote-Control-YG493OD-EB/301162064) and it's become clear that the remote itself stores the entire state of the fan, so any time the remote is used, HomeKit's state gets confused (not only for the fan light, as is documented both in the Bond software and here with the toggle switch you've exposed), but also the state of the fan speed.

Often a fan will think it's on or off but will actually be the opposite, if I tell homekit or siri to turn it on, it's pretty clear the Bond bridge isn't sending any signal to that effect. Is there a way to force this so that the RF signal is actually sent? Ideally this is a Bond setting I'm missing, but if not it'd be a great feature in this bridge. I have half a mind to automate a "jiggle" that switches between speeds rapidly to force it to send the signal.

**Comment by searls** [comment]
@chrismerck thank you for the added clarification! Knowing that's what "state remote" means will help me as I navigate the code & docs

I'd love for the combination of Siri/HomeKit + Bond to be reliable enough that I could confidently shove all these remotes into a drawer, but unfortunately they combine for a ~10% failure rate, which is too high for my family members to put up with. I wonder if there's a workflow I might devise to accomplish this…

**Comment by aarons22** [comment]
hey @searls - there is already a feature in this plugin where you can enable a "toggle state" switch (add `include_toggle_state: true` to your config for this plugin). This adds an additional button in the HomeKit accessory that toggles the state in Bond (similar to changing the state in the Bond app). 

This isn't ideal but it's about the best you'll get. Note that this will add a toggle switch for _all_ of your fans, but I'm working on an upcoming feature that will allow you to choose which devices you want the toggle switch for.

**Comment by searls** [comment]
Thanks @aarons22! Is this toggle state switch only for the light or does it apply to the fan as well?

**Comment by aarons22** [comment]
Great question. Unfortunately it's only for the light. If Bond ever releases a way to fix fan state I'll try to add it here, but I can't really see that happening as the fan state is more complex

**Comment by chrismerck** [comment]
If I understand correctly, the request here is not to change the fan's state, but rather the Bond Bridge's _belief_ about the fan's state.

You can change the Bridge's belief by PATCHing the devices/{x}/state endpoint. This will not cause any transmission to be sent to the fan.

---

There's also another way of dealing with a similar problem with most CF remotes that *don't* have an LCD screen. Say you want to have a button on a UI (whether in an app, or a physical button) to operate the fan light. If the fan has a toggle-based light command, then use a single toggle button on the UI mapped to the ToggleLight action. This ensures that, even if the Bridge is mistaken about the true state of the light, the user intent is carried out.
