### ISSUE TITLE
Switch to Local API

### ISSUE THREAD

**Issue by ylor** [aarons22/homebridge-bond#16]
Switching to the local will likely be a net win all around.

Beta sign up: https://forum.bondhome.io/t/bond-local-api-beta-sign-up/250
Local API docs: http://docs-local.appbond.com/#section/Glossary/BOND-Bridge

**Comment by aarons22** [comment]
@ylor I create a new plugin using the v2 API, which can be found here: https://github.com/aarons22/homebridge-bond-v2
