### ISSUE TITLE
For devices in scene, send group command

### ISSUE THREAD

**Issue by MattGeale** [aarons22/homebridge-bond#195]
**Is your feature request related to a problem? Please describe.**
No real issue, but is there way to have accessories that are grouped in the Home App trigger at the same time? I have 16 blinds which are setup fully in the Bond app and are individual blinds with no more channels to setup grouping at a blind level (16 channel remote is maximum without buying another remote). As such, I have grouped them in the home app which works a treat, but the problem is, they're waiting a brief second or two before the other blind moves. eg Scene A contains Blind X and Blind Y...If I trigger Scene A from the HomeKit app, Blind X moves first, Blind Y moves last. I want to see if there is a way for the Homebridge app to wait until both blinds respond to the Bond bridge and then when response is received, move them at the same time.

**Describe the solution you'd like**
A way for the homebridge application to 'wait' until the accessories that are grouped in the Home App to respond to the Bond Brige before moving.

**Describe alternatives you've considered**
In progress of liasing with Bond themselves if theres a way to group accessories in the Bond App. Cannot seem to find a way to do this currently. If I'm missing something, pls advise.

**Additional context**
N/A

**Comment by chrismerck** [comment]
Hi @MattGeale , that would be a Bond Home question rather than a HomeBridge question, because it depends on how your shades communicate at the RF level. I suggest jumping to our forums and @mentioning me (@merck): https://forum.bondhome.io/

**Comment by MattGeale** [comment]
> 

Hi @chrismerck,

Ok I'll dump the question in Bond Home and attach the additional information requested.

Cheers

**Comment by MattGeale** [comment]
Closing Issue - Not Homebridge Fault and temporary solution reached.
Posting link for anyone else who might hit same block

https://forum.bondhome.io/t/how-to-eliminate-popcorn-effect-for-somfy-rts-shades/2939
