### ISSUE TITLE
SetPosition visualisation/implementation/control in Home app

### ISSUE THREAD

**Issue by MattGeale** [aarons22/homebridge-bond#196]
**Is your feature request related to a problem? Please describe.**
Nup - just an enhancement for future itterations of this app. Happy to betatest if required!

**Describe the solution you'd like**
With more blinds being supported by Bond, can we get the Homebridge app updated to display/invoke SetPosition? Maybe a slider to show where the blinds stop and where they currently are stopped. The blinds respond to a certain extent to the Bond bridge showing that they've been opened/closed so perhaps since the Bond App itself shows the percentage of where the blind has been opened/closed, perhaps we could get this shown on Homekit?

**Describe alternatives you've considered**
Currently just controlling SetPosition through Bond App but in perfect world would like to see SetPosition make its way to the Home app.

**Additional context**
Something like this.
![image](https://user-images.githubusercontent.com/88370061/148140841-e2088853-a770-4a4e-9330-df139097c9c6.png)

**Comment by Fofer** [comment]
Good thinking, and thanks for mentioning this functionality. In the meantime, check out this clever implementation, it doesn't rely on SetPosition so therefore doesn't need a Bond Pro bridge.  https://github.com/dxdc/homebridge-blinds
