### ISSUE TITLE
Ability to Assign each Control to its own location (room).

### ISSUE THREAD

**Issue by DCMarine** [aarons22/homebridge-bond#22]
As a lot of these these devices are base on Frequency and not IR, can it be looked at with the ability to have the controls assigned to its own room.    As it stand right now, they all go together.

**Comment by aarons22** [comment]
Is the request to have the room be pre-selected in HomeKit when it's being added? Not sure I totally follow.

**Comment by aarons22** [comment]
Closing this since I haven’t heard back and it was posted with the pre-v2 plugin.
