### ISSUE TITLE
Turning off fans via Automation not working

### ISSUE THREAD

**Issue by ylor** [aarons22/homebridge-bond#27]
Hello and thank you for taking over this project and supporting the v2 API!

It's been working great for the most part, the only issue I've been having so far is with regard to setting up automations. Turning fans ON via automation works as it should, however turning fans OFF via automation does not.

Things I have tried:

* Removing and readding the plugin
* Removing and readding homebridge 
* Deleting accessories/persist folders

**Comment by aarons22** [comment]
Sorry about that. I just fixed this issue in [2.0.1](https://github.com/aarons22/homebridge-bond/releases/tag/2.0.1). Can you update and let me know if that fixes your issue?

**Comment by ylor** [comment]
Yes. Thank you for such a quick fix.
