### ISSUE TITLE
NAB - Shades?

### ISSUE THREAD

**Issue by iRayanKhan** [aarons22/homebridge-bond#33]
I saw shades were added and was curious as to which ones would be supported. I for one and on the hunt for HomeKit shades, or Homebridge ones, so shades is interesting especially if bond can handle any shade. 
https://github.com/aarons22/homebridge-bond/projects/1#card-26992587

**Comment by iRayanKhan** [comment]
Don't know how to self assign "feature-request" instead of bug as it did it on it's own.

**Comment by jdlambert** [comment]
> shades is interesting especially if bond can handle any shade.

At the moment, Bond only has out-of-the-box support for Somfy RTS shades.

**Comment by iRayanKhan** [comment]
Dang that sucks, I'm still on the hunt for HomeBridge shades, maybe the Ikea ones, but they don't have custom sizes.
