### ISSUE TITLE
For non-bridge devices, plugin does not support fan speed correctly

### ISSUE THREAD

**Issue by aarons22** [aarons22/homebridge-bond#34]
The plugin uses the `commands` endpoint to determine the speed range of a fan. For non-bridge fans, we can use the `properties` endpoint to get the `max_speed`.

A lot of context for this can be found in this issue: https://github.com/aarons22/homebridge-bond/issues/13

cc: @KCFT23

**Comment by KCFT23** [comment]
Thank you!  Looking forward to testing this for you when you have time to work on this feature request.

**Comment by aarons22** [comment]
@KCFT23 I just [2.2.0](https://github.com/aarons22/homebridge-bond/releases/tag/2.2.0) with this fix! Turns out it was pretty straight forward so I went ahead and knocked it out.

You'll need to clear your cachedAccessories for this to work! Please report back 😄

**Comment by KCFT23** [comment]
It works!  Thanks so much for taking care of it so quickly!  It looks great, and I tested the fan speed control, the light, and I see the reverse button too (I have not tested that one yet).  It does not have dimming capability for the light, but I rarely use that anyway.  You can close this issue!
