### ISSUE TITLE
Can't control fan status over Shortcuts

### ISSUE THREAD

**Issue by iRayanKhan** [aarons22/homebridge-bond#35]
**Bug Description**
In iOS 13.2 I was doing a Shortcuts automation to get the state of the fan and 
```
if fan = on
turn fan off,
else
fan on.
```
Obviously not real code, I'll share the shortcut once I get home, but I have an NFC sticker that when I place my phone on will toggle the state of accessories.
When trying to control the fan via it, it sets the it to the desired speed, the home app reflects the speed change, but the fan it's self had no change unless manually changed. 
It may be good to note that the Fan Light accessory can be toggled from shortcuts.

**Expected behavior**
When automation sets fan speed to 0, fan should turn off in real life.

**Screenshots**
Adding once I get home.

**Information (please complete the following information):**
 - Plugin version V2.2.0
 - V2.x (Latest) 
 - iOS version 13.2

**Additional context**
This shortcut works for other accessories and Homebridge accessories, including the fan's light accessory, just not the fan (speed).

**Comment by vdotn** [comment]
Can you share the shortcut? Also do you have a home hub? And if so what device/iOS version?

**Comment by iRayanKhan** [comment]
Yeah.
On my Mac so I'll send the shortcut asap.
Home Hubs:
1) Apple TV 4K (3 of them 1 is the main one that's always connected, left the others on disabled)
2) HomePod (2 of them always on standby)
All on the latest beta build
Shortcut I can send in a few hours as I don't have my phone on me currently.
As I said before it's weird how the Fan Light accessory toggles via the shortcut, but the fan speed it self doesn't. 
Also the shortcut is an automation that runs a select shortcut via NFC sticker (again fan light works, just not fan speed) and can be run without a NFC sticker.

**Comment by vdotn** [comment]
I’ll test your shortcut against my setup for ya once you post it.

Was wondering if your issue is related to what I saw when my HomePod (iOS 12.4) took over as home hub and everything went to shit, but it doesn’t appear to be your case.

**Comment by iRayanKhan** [comment]
My address is blurred since this is a public space obviously and can’t share the shortcut directly, but it’s easy to make as seen in the screenshots.

**Comment by iRayanKhan** [comment]
Love how they didn't attach.
Here they are:
![IMG_1172](https://user-images.githubusercontent.com/34495712/66430559-f80b9c00-e9df-11e9-86d3-e31f04a4ed99.jpg)
![IMG_1173](https://user-images.githubusercontent.com/34495712/66430568-fc37b980-e9df-11e9-85b4-483354ad0b88.jpg)

**Comment by iRayanKhan** [comment]
Automations via the home app seems to be broken too. This doesn't seem like an OS level bug, since every other accessory works homebridge. or not. No clue what's happening. Gonna get logs later tomorrow and attach them.

**Comment by iRayanKhan** [comment]
I somehow have 2 versions of bond, the one by EDC and the fork you made before It was merged originally. Found this when trying to add a TV, they are fighting over each other. I'm gonna have to re-do my homebridge setup anyways since I have lots of old versions of plugins it seems and a fresh install with the latest nom version should fix things

**Comment by dxdc** [comment]
@iRayanKhan just playing with this a little bit, I wonder if the problem is that you're looking for the Fan Power State. It seems like this never gets touched by `homebridge-bond` -- essentially -- it sets the fan *speed* to 0%, 33%, 66%, or 100%, instead of *also* turning off the fan at 0%.

This is strange, because in the Home app itself, I CAN turn off the fan by just clicking on the icon.

> When automation sets fan speed to 0, fan should turn off in real life.

Agreed, but I think this is probably a bug in the homebridge code because it's not turning off at 0.

So, I think the following psuedo-code would be better:
```
Get Power State of Fan
Get Fan Speed of Fan

if fan = off {
  // fan off
} else if Fan Speed = 0 {
  // fan ON, but set to 0
} else {
 // fan ON, and speed > 0
}
```

Also, one thing I've discovered with Shortcuts (for example, with screen brightness) is that you have to use a float to set % numbers. So, on a 3 speed fan, I think you have to set the fan speed to 0.33, 0.66, or 1.0, though I haven't tested this.

**Comment by iRayanKhan** [comment]
Closed:
Re-did my whole HomeBridge set-up and it seems to be working now. I guess it kept the v1 plugin or whatever, but make sure if this happens to anyone to remove v1 from
```/usr/lib/node_modules```
