### ISSUE TITLE
V2.9.1

### ISSUE THREAD

**Issue by iRayanKhan** [aarons22/homebridge-bond#37]
Has anyone been brave enough to go from V2.8.2 -> V2.9.1? Me not having a spare device puts me off from upgrading the firmware since I don't know if it will break anything. If anyone is on V2.9 let me know if it works for you.

**Comment by aarons22** [comment]
I was hoping there would be a change log posted somewhere but didn’t find anything on the forum :/

I probably won’t upgrade for a bit while I’m still working through some of these features.

**Comment by JT-EOD** [comment]
I just updated to v2.9.1, and I haven't seen any issues so far.

**Comment by chrismerck** [comment]
I just moved the release notes to a more visible spot in the forum: https://forum.bondhome.io/t/bridge-firmware-v2-9-1/921

**Comment by aarons22** [comment]
@chrismerck thanks!

**Comment by iRayanKhan** [comment]
Closed:
- Change log found
- Users reports version is compatible
