### ISSUE TITLE
Worth upgrading firmware?

### ISSUE THREAD

**Issue by dkahia** [aarons22/homebridge-bond#38]
I am on v1 firmware with the v1 homebridge plug-in. 4 of my 5 ceiling fans work as expected, with the 5th having a self automated temperature controlling remote and has not been critical.  I am not sure if my bond will upgrade to v2, but expect if it did that I might gain fan 5. 

I admit I’m a bit leery to upgrade my working system. Does the v2 api and bond plug-in offer any benefits over my working v1 implementation?  Is it worth the effort and risk of upgrading my bond and the plug-in?

**Comment by aarons22** [comment]
If everything is working as expected, I wouldn’t say there is any benefit at the moment.

The real benefit will come when I get a chance to add support for the newer devices only available over v2 API, which was my driving factor in rewriting the plugin.

**Comment by dkahia** [comment]
Thank you. I’ll keep an eye on your effort and take the plunge when it looks like it will benefit me. 

Thank you for your work. I am sure there are many with v2 devices that didn’t have an option before you took this on.
