### ISSUE TITLE
6 Fan Speeds

### ISSUE THREAD

**Issue by twentyNoise** [aarons22/homebridge-bond#4]
Our fans have 6 fan speeds. It would be great if the Fan resolution was split into 6 or something similar. Thanks!

**Comment by iRayanKhan** [comment]
I do believe this is a limitation on bond's end as iirc bond supports unto 3 fan speeds. Maybe create another bond fan with the other 3 controls?

**Comment by plainsane** [comment]
See if my pull request helps.  I was having a handful of issues, speed, losing fan state on reboot and general out of sync issues.  I added an additional switch so that I can reset the state of the light and fan speed inside Homekit.

I think the speed issue is caused by the fact that Homekit can send a rotation update followed by a power on to the fan, which the code would call the power on method...I have changed that behavior.

**Comment by iRayanKhan** [comment]
@plainsane How do I install your version via npm?

**Comment by iRayanKhan** [comment]
Fixed: #5

**Comment by twentyNoise** [comment]
> See if my pull request helps. I was having a handful of issues, speed, losing fan state on reboot and general out of sync issues. I added an additional switch so that I can reset the state of the light and fan speed inside Homekit.
> 
> I think the speed issue is caused by the fact that Homekit can send a rotation update followed by a power on to the fan, which the code would call the power on method...I have changed that behavior.

I finally got around to upgrading to the latest version and the reliability issues, speed change issues are fixed.

For the 6 Fan Speeds I once again just edited the Index.js to support the 6 speeds. Someone more versed in js than myself should simply code this to base the number of speeds on what is shown in the Bond account.

Anyway, the plugin is MUCH more reliable now with your updates.

Thanks again!

**Comment by twentyNoise** [comment]
I just installed the new version and looks like I’m only getting speeds 1 (33%), 2 (66%) and 3 (100%).

Also, when I click the Fan tile in the Home app to shut the fan off, nothing happens.

Thanks for your work on this!

**Comment by aarons22** [comment]
Yeah more than 3 speeds is on my list. I’m hoping to get that knocked out in the next few days.

As for the fan tile issue, what version of iOS are you running?

**Comment by twentyNoise** [comment]
Cool, that’s great.

I just installed iOS 13. I wish I hadn’t because the Home app has become unusable: it freezes while updating statuses, I get ‘No Response’ all over the place. iOS 12 Home App has no issues there, which reminds me, I’ll check this Fan tile / off issue in iOS 12.

**Comment by aarons22** [comment]
@twentyNoise I fixed the Fan tile off state issue, and added support for more than 3 speeds! please update and create a new issue if you have any other problems

**Comment by twentyNoise** [comment]
@aarons22 Brilliant! it works great! Thank you so much for updating the plugin, it’s working perfectly now and it’s as responsive as the Bond Home app.
