### ISSUE TITLE
Dimming Support

### ISSUE THREAD

**Issue by iRayanKhan** [aarons22/homebridge-bond#40]
This issue is a feature request for the addition of Dimming the fan light.

Currently bond supports dimming of the fan light and it would be great to extend that into this plugin.

My issue, is that my fan has only 1 button in relation to light, a simple toggle where you either hold the top of the button to brighten the bulb or hold the bottom of the button to dim it.

Instead of a separate accessory to handle light dimming, I feel like it should be a config parameter to specify if a light dim's. Now on to another issue that may arise, not all fans can support dimming. 

My assumption is for the service to add a slider like lamps do already if brightness can be toggle, the ```lightToggle``` button be replaced with a slider.

As I mentioned earlier some fans may or may not support dimming so a slider wouldn't work unless the API can report it supports dimming, or send multiple requests to mock holding the button up or down.

If the resolution were to require a config update, It'd may have to specify each device configured on your bond and specify type such as shades, fan, fan with light, fan without light, fan with dimming light, fireplace, etc. I'm sure there is a better way to tackle this and I probably got off track a little, but let the forks begin.

**Comment by aarons22** [comment]
With the Bond API, dimming can only be controlled by [Start / Stop actions](http://docs-local.appbond.com/#section/Features/Misc-including-dimmers), so there is no way to specify the dim value.

Similar to your fan, it would have to be a HomeKit button/switch to start/stop the dim action, or we could setup the plugin to start/stop for a specific interval based on a button on the accessory. For example, you tap the HomeKit button/switch, it starts dimming for a second, then stops, and in turn, turns the HomeKit button off.

**Comment by iRayanKhan** [comment]
> For example, you tap the HomeKit button/switch, it starts dimming for a second, then stops, and in turn, turns the HomeKit button off.
>
What if the slider could do it? Like by default have the light set to 100% and then when it goes down for example 10% and reports a request of wanting 90% it does the brightness down request once. Unless there's something I'm not getting, I glanced for the api docs too.

**Comment by aarons22** [comment]
The assumption that it starts off with full brightness won't hold well over time. It also shifts the source of truth from the Bond to HomeKit, which (to me) is a non-starter. The only way to guarantee a consistent experience is to use the Bond API as the source of truth and rely on it for the current state.

Others might disagree with this stance, but it's core to how I've structured the plugin to operate (I don't think introducing Reset switches is a great approach either, which is how the pre-v2 plugin got away with dealing with state).

**Comment by iRayanKhan** [comment]
I have a theory I want to test on my bond it's self for brightness, but if one of my fans does have dimming control and I try to add it into this plugin, would it crash to just add a light toggle?

**Comment by aarons22** [comment]
@iRayanKhan might be easiest if you just use the API directly to test anything out!

**Comment by aarons22** [comment]
I've taken a stab at this in [2.4.0](https://github.com/aarons22/homebridge-bond/releases/tag/2.4.0) (opt-in using the `include_dimmer` config parameter). I don't love the way HomeKit groups the switch in the UI because regardless of the order of the code, it always makes the dimmer switch the right vertical toggle and the light the bottom circular light switch. This is why I made it an opt-in feature for now.

The other option is to add a completely new accessory just for the switch, but that will require quite a bit more work to refactor the structure of the plugin. 

Give it a try and let me know how it works out for you!

**Comment by vdotn** [comment]
Interestingly I'm not getting a second switch for dimmer at all on either fan. Both have a dimmer action in the bond app. I tried nuking cached accessories, no difference.

What did I screw up?
Config snip:
```

	{
		"platform":"Bond",
		"bonds": [
			{
				"ip_address": "10.0.1.48",
				"token": "<token>",
				"include_dimmer": "true"
			}
		]

	},
}
```

**Comment by aarons22** [comment]
@vdotn can you post a screenshot of your device commands from the Bond app? Curious which ones you have setup. I'm keying off of the existence of the `StartDimmer` action, so I'm wondering if there is something different about your commands.

**Comment by vdotn** [comment]
Here you go. I’ll also get a dump of what actions the API returns in a little bit. That might actually be more helpful to you. 
![A0E1D3DD-ECEB-4924-889E-141986982129](https://user-images.githubusercontent.com/36348492/67105310-8b8a5d00-f196-11e9-8b2b-46722aa0c7a6.png)

**Comment by vdotn** [comment]
Actually bedroom fan might be a better example it only has one light and is pretty vanilla. 
![D1BDB2F9-C407-4A69-8905-8BFB42B0964E](https://user-images.githubusercontent.com/36348492/67105395-b2489380-f196-11e9-850a-a117631c3742.png)

**Comment by iRayanKhan** [comment]
Since most remotes have the ability to change their own frequency on the back or inside of it to match the fan, what if we just bought a remote and program it to the bond with the same frequency, but the remote has proper dim/brighten actions? To bond you'd be adding an action rather than a new remote, since same frequency.

**Comment by vdotn** [comment]
I don’t know if most ceiling fans take discrete dim up and dim down actions. I always thought their dimmers are primitive and just went up and down in a loop. Would be awesome if you’re right, let us know what your testing shows!

**Comment by iRayanKhan** [comment]
>
I always thought their dimmers are primitive and just went up and down in a loop.
>
Sadly I think that may be the outcome. After November 2nd I can buy whatever needed, so I'll buy it right after then.

**Comment by vdotn** [comment]
@aarons22 Here's the output that the API gives for actions:

```
iMac:~ vitaly$ curl -H "BOND-Token: $TOKEN" -i http://10.0.1.48/v2/devices/0000001a/actions | tr ',' '\n'

HTTP/1.1 200 OK
Content-Length: 618
Content-Type: application/json; charset=utf-8

{"_":"3afef46e"
"SetSpeed":{"_":"da6afd07"}
"ToggleUpLight":{"_":"a5134ca1"}
"TurnOff":{"_":"1b518974"}
"ToggleDownLight":{"_":"932840f1"}
"StartDimmer":{"_":"b8ff06fd"}
"ToggleDirection":{"_":"5867ea51"}
"Stop":{"_":"fe605cfa"}
"TogglePower":{"_":"905a34df"}
"TurnOn":{"_":"027ee108"}
"IncreaseSpeed":{"_":"06913217"}
"DecreaseSpeed":{"_":"a317c680"}
"SetDirection":{"_":"5ba487e9"}
"ToggleLight":{"_":"3075e5f3"}
"TurnLightOn":{"_":"75390869"}
"TurnLightOff":{"_":"9dd615cb"}
"TurnUpLightOn":{"_":"bea1dad2"}
"TurnUpLightOff":{"_":"9a4a1fd1"}
"TurnDownLightOn":{"_":"569c5812"}
"TurnDownLightOff":{"_":"63165e63"}}
```

**Comment by chrismerck** [comment]
> I always thought their dimmers are primitive and just went up and down in a loop.

This is true for most r/c ceiling fans where the remote does *not* have an LCD screen. There's just a single RF signal for "light" which, when sustained, causes the receiver to dim up/down in a cycle. We've thought a lot about how to deal with that, but there's really no good answer, and we don't make an attempt to dead-reckon the brightness.

That's why @vdotn's device is only exposing the Light feature (TurnLightOn, etc.) rather than also exposing the Brightness feature (SetBrightness, etc.).

---

However, if you've got a remote with an LCD screen (like this https://www.amazon.com/Universal-Receiver-Complete-Thermostatic-L3HFAN9T/dp/B073JPCL1G/ref=sr_1_6?keywords=ceiling+fan+remote+control+kit+LCD&qid=1571436225&sr=8-6) chances are the underlying RF protocol supports setting absolute brightness. In these cases, you will see SetBrightness available via the API.

(Best case scenario is the forthcoming Smart by Bond aftermarket receivers (like https://www.homedepot.com/p/Universal-Smart-Wi-Fi-4-Speed-Ceiling-Fan-Remote-99434/311264804), but alas those are not yet in stock online.)

**Comment by iRayanKhan** [comment]
Closing; New version supports this action and I guess primitive dimmers need an expensive remote or aftermarket receiver.

**Comment by thevcao** [comment]
I discovered that the issue (for vdotn and myself) is that the include dimmer config needs to be set in the root of the platform config ie:

’’’
{
		"platform":"Bond",
		"include_dimmer": true,
		"bonds": [
			{
				"ip_address": "<ip>",
				"token": "<token>"
			}
		]
}
’’’
