### ISSUE TITLE
Firmware v. 2.9.2 released

### ISSUE THREAD

**Issue by vdotn** [aarons22/homebridge-bond#44]
https://olibra.zendesk.com/hc/en-us/articles/360033791031-bond-bridge-CURRENT-Application-and-Firmware-versions-using-the-bond-home-application

Seems like a release with minor bug fixes. I updated and it's been working fine for me.

ALSO - and this is the bigger news - it seems that at some point between when I checked in June and now, Bond brought firmware parity between ZZ devices and the rest, so all bonds can be updated to version 2.x now. This is fantastic news and probably means we can completely axe the 1.0 branch of this plugin.

**Comment by chrismerck** [comment]
> Bond brought firmware parity between ZZ devices and the rest [A/B]

Yes, getting the same firmware to run on both versions of hardware was epic...

Details on the V2 platform here, if you're curious about the 1.0 - 2.0 changes: https://forum.bondhome.io/t/bond-v2-platform/466

**Comment by vdotn** [comment]
@chrismerck thanks for this. Great write up and I love the transparency.
