### ISSUE TITLE
Getting  ERR:  Bonds array is required but missing from config.json

### ISSUE THREAD

**Issue by LeviJSmith** [aarons22/homebridge-bond#46]
**Describe the bug**
Getting the following error for bond in homebridge. 

 [10/26/2019, 3:45:01 PM] [Bond] Initializing Bond platform...
[10/26/2019, 3:45:01 PM] [Bond] ERR: bonds array is required but missing from config.json

**Information (please complete the following information):**
 - Plugin version - homebridge-bond v2.4.0
 - Bond firmware version - v2.9.4
 - iOS version - 13.1.3

**Additional context**
Bond hasn't worked for a couple of weeks.  Get an error when it tries to load plugin saying ERR:  Bonds array is required but missing from config.json.  Below is the bond portion of my config.json

{
            "platform": "Bond",
            "bond_ip_address": "BOND IP ADDRESS",
            "bond_token": "MY BOND TOKEN"
        }

**Comment by aarons22** [comment]
There was an update to the config structure. It should be:
```
        "platform": "Bond",
        "bonds": [
            {
                "ip_address": "BOND IP ADDRESS",
                "token": "MY BOND TOKEN"
            }
        ],
```

Keep in mind some users are having issues with fan speed on 2.4.0, so you might be better off on 2.3.2 (see https://github.com/aarons22/homebridge-bond/issues/45)

**Comment by LeviJSmith** [comment]
I can't believe I missed that in the config.  Updated the config structure and everything working good again.  Thx for your help.  Have a great day!!
