### ISSUE TITLE
[Bond] ERR: bonds array is required but missing from config.json

### ISSUE THREAD

**Issue by Crazywill1** [aarons22/homebridge-bond#49]
I had it working on my Hoobs homebridge. was working great I uninstalled it to do a tutorial. tried to reinstall it and not showing up. I reinstalled homebridge from scratch update plugin, bond hub, and homebridge. This is the error it get.
[Bond] Initializing Bond platform...
[Bond] ERR: bonds array is required but missing from config.json
Loading 2 accessories...

 - Plugin version (run `npm list -g homebridge-bond`v2.5.0)
 - Bond firmware version v2.9.4
 - iOS version (13.2)

Thank you for your time.

**Comment by aarons22** [comment]
The config changed a few versions back:
```
        "platform": "Bond",
        "bonds": [
            {
                "ip_address": "<BOND_IP_ADDRESS>",
                "token": "<BOND_TOKEN>"
            }
        ],
```

Can you make sure your config looks like this?

**Comment by Crazywill1** [comment]
I tried that was not working after playing with it for hours the 1 time this was what would work with out errors but now nothing. 
        {
            "platform": "Bond",
            "bond_ip_address": "<BOND_IP_ADDRESS>",
            "bond_token": "<BOND_TOKEN>"
        }
The original code would just give me errors. 
Thanks for the reply.

**Comment by aarons22** [comment]
Sorry, I'm a little confused. You're saying the config I posted isn't working on 2.5.0?

**Comment by Crazywill1** [comment]
Sorry yes the homebridge configuration file. No I uninstalled it an reinstall it. tried rebooting it several times. It's just not working and I had it working with that code. Could it be the update to Bond? v2.9.4.

**Comment by aarons22** [comment]
Possibly, but not likely. Can you clear you cached accessories? (`rm -rf ~/.homebridge/accessories/cachedAccessories`)

Also, just to confirm, you’re still seeing `ERR: bonds array is required but missing from config.json`

**Comment by Crazywill1** [comment]
I'v tried that as well (rm -rf ~/.homebridge/accessories/cachedAccessories)
[10/31/2019, 7:07:48 PM] [Bond] Initializing Bond platform...
[10/31/2019, 7:07:48 PM] [Bond] ERR: bonds array is required but missing from config.json
[10/31/2019, 7:07:48 PM] Loading 2 accessories...

I'm sorry man feel like I'm harassing you. I'v never asked on these form before. It's just I had it working. I took particular notes and backed up files. It's driving me crazy LOL.

**Comment by aarons22** [comment]
No worries! It can be frustrating when things seem like they're supposed to work but don't 😅 

It's odd that error is showing up, because it should only happen _if_ the `bonds` key is missing from the config. Would you mind posting a screenshot of your config?

**Comment by Crazywill1** [comment]
So weird every time I put your code in I would get an error. someone just posted there code and it worked. looks just like yours. Maybe it was something with a copy and paste or Hidden characters.
{
            "platform": "Bond",
            "bonds": [
                {
                    "ip_address": "<ip address>",
                    "token": "<token>"
                }
            ]
        }
    ]
}

Thanks man I'm up and running again.

**Comment by aarons22** [comment]
Great to hear!
