### ISSUE TITLE
No Dimming Feature

### ISSUE THREAD

**Issue by chrisoehmke** [aarons22/homebridge-bond#51]
In my Bond app, I have the option to dim my lights with the start/stop, but I don't have the option to dim in HomeKit. I have added the dimmer parameter and still have nothing. Attached is my config.json. There aren't any missing items in my config, I just removed them for this upload.

![Screen Shot 2019-11-08 at 6 00 37 PM](https://user-images.githubusercontent.com/57383772/68518744-fc330f80-0252-11ea-8a5e-a09e0da65dd3.png)

**Comment by aarons22** [comment]
The dimming feature is a bit experimental. Right now, it gets added a second light to the fan. Can you confirm you don't see the second light in the Home app?

Also, debug logs during your homekit startup would also be helpful.

**Comment by chrisoehmke** [comment]
I do not see a second light in the Home app.

Home App:
![IMG_0751-1](https://user-images.githubusercontent.com/57383772/68640293-e466c000-04cc-11ea-936c-abe4a1cc42c8.png)

My Bond App:
![IMG_0752-1](https://user-images.githubusercontent.com/57383772/68640301-e9c40a80-04cc-11ea-98bc-e23a723e32ce.png)

I can't find any logs for my homebridge. The are no homebridge logs in /var/log

**Comment by aarons22** [comment]
@chrisoehmke I just looked at your config again and realized what the issue is. `include_dimmer` and `debug` need to go outside of the bonds array:
```
    {
        "platform": "Bond",
        "include_dimmer": true,
        "debug": true,
        "bonds": [
            {
                "ip_address": "<BOND_IP_ADDRESS>",
                "token": "<BOND_TOKEN>"
            }
        ],
    }
```

**Comment by chrisoehmke** [comment]
That fixed it, thanks.
