### ISSUE TITLE
Dimmer for light not present?

### ISSUE THREAD

**Issue by montanaishome** [aarons22/homebridge-bond#54]
Added “include_dimmer”: true to my configuration, but there is no panel to dim the lights in my home app.  I can dim the lights from the bond app, though. Remote is a litex with an lcd panel.

**Comment by aarons22** [comment]
Can you confirm you config looks like this?
```
"platforms": [
    {
        "platform": "Bond",
        "include_dimmer": true,
        "bonds": [
            {
                "ip_address": "<BOND_IP_ADDRESS>",
                "token": "<BOND_TOKEN>"
            }
        ],
    }
],
```

And just to be clear, it shows up as a light switch within the Accessory group.

**Comment by aarons22** [comment]
@montanaishome any update on this?
