### ISSUE TITLE
New user - Cannot find devices

### ISSUE THREAD

**Issue by reffr** [aarons22/homebridge-bond#56]
I'm using the new bond app on iPhone. It works great. My other homebridge devices are working great. I'm on firmware v2.9.5.

Does the Bond ID go anywhere in the config file?

If I try to access the bond by web browser directly by entering an IP address I get the screen shot attached. 
<img width="469" alt="Screen Shot 2019-11-28 at 6 09 49 AM" src="https://user-images.githubusercontent.com/30008361/69805221-d8098500-11a5-11ea-846d-7a936fe056d3.png">

I'm very thankful that you are helping people troubleshoot!  Thanks so much!

-Rob

Here is what I added to my config file:
           "platform": "Bond",
            "bonds": [
                {
                    "ip_address": "192.168.1.110",
                    "token": "[Copied from iPhone]"
                }
            ]

[2019-11-28 06:02:43] [Bond] ERR: A request error occurred: Error: connect ENETUNREACH 192.168.1.110:80 - Local (0.0.0.0:0)

[2019-11-28 06:02:43] [Bond] 0 cached accessories were loaded
[2019-11-28 06:02:43] [Bond] Getting devices...
[2019-11-28 06:02:43] [Bond] 0 devices were found on this Bond.
[2019-11-28 06:02:43] [Bond] Attempting to add 0 devices that were not previously added.

**Comment by aarons22** [comment]
It sounds like the bond is unable to resolve your IP address. Can you confirm that running the curl command found in the bond v2 api docs works for you? http://docs-local.appbond.com/#section/Getting-Started/Check-Bond-Version

```
curl -i http:/<BOND_IP>/v2/sys/version
```

**Comment by aarons22** [comment]
@reffr happy to help with this issue but need more info. If not, I'll close this issue
