### ISSUE TITLE
Every So Often All Names Are Reset

### ISSUE THREAD

**Issue by ntableman** [aarons22/homebridge-bond#58]
**Describe the bug**
When I wake up in the morning all my Bond devices are renames this like:

Garage Bedroom Garage Bedroom Ceiling Fan

When I last left it, it was called Garage Bedroom Ceiling Fan

**Expected behavior**
Keep the name

**Information (please complete the following information):**
 - Plugin version (run `npm list -g homebridge-bond` in terminal)

homebridge-bond v2.5.3

 - Bond firmware version
latest

**Comment by aarons22** [comment]
@ntableman This may be due to a recent PR: https://github.com/aarons22/homebridge-bond/pull/57

If you adjust the name in HomeKit when adding the accessory, it shouldn't rename them. Does this happen every morning?

**Comment by ntableman** [comment]
Yes...I rename them and then the next morning they are reset and back to Default Room. LMK what debug info I can get you.

**Comment by aarons22** [comment]
Admittedly I wasn't running the most recent version on my homebridge server, so I just updated and will see if I can replicate the issue.

**Comment by aarons22** [comment]
Just curious, do either of these posts sounds like the same issue? I happened to catch these in the past couple days and it sounded similar:
https://www.reddit.com/r/HomeKit/comments/enoaii/my_home_reverts_itself_back_to_old_settings/
https://www.reddit.com/r/HomeKit/comments/enmjqy/homekit_keeps_reverting_back_to_old_settings

**Comment by ntableman** [comment]
Sorry, I dont use reddit given their place in making the world less safe and harmonious. That and when it was sold for many millions all I got was a donut.
