### ISSUE TITLE
Bond Plugin for V2

### ISSUE THREAD

**Issue by wnaylor** [aarons22/homebridge-bond#60]
Aaron,
What is the problem here. Please help. The Bond IP address is 192.168.1.48 and the token is correct. I have established that through the instructions but I am getting these error messages and no accessories are found.

[Bond] Initializing Bond platform...
[1/9/2020, 2:43:46 PM] [Bond] ERR: A request error occurred: Error: Invalid URI "http:///%3C192.168.1.48%3E/v2/devices"
[1/9/2020, 2:43:46 PM] [Bond] Error getting device ids: TypeError: Cannot convert undefined or null to object
[1/9/2020, 2:43:46 PM] [Bond] 0 cached accessories were loaded
[1/9/2020, 2:43:46 PM] [Bond] Getting devices...
[1/9/2020, 2:43:46 PM] [Bond] 0 devices were found on this Bond.
[1/9/2020, 2:43:46 PM] [Bond] Attempting to add 0 devices that were not previously added.

**Comment by aarons22** [comment]
Based on what you posted, it looks like there might be some extra characters in your IP address. Can you post your config file?

**Comment by wnaylor** [comment]
{
	"bridge": {
		"name": "Homebridge",
		"username": "C8:28:3D:E9:CE:30",
		"port": 51826,
		"pin": "041-78-280"
	},

	"platforms": [{
			"platform": "SensiboSky",
			"name": "Sensibo",
			"apiKey": "cTzFrriiwg0PEQRJS0KLAfOI7Wv3UI",
			"timeLapse": 5,
			"ai": true,
			"hideFan": false,
			"hideHumidity": true,
			"fixedState": "auto"
		},
		{
			"platform": "Bond",
			"bonds": [{
				"ip_address": "<192.168.1.48>",
				"token": "<c2b0dfeeba8034cc>"
			}
		]
		}
	]
}

**Comment by aarons22** [comment]
Remove the < and > characters from both IP address and token

**Comment by wnaylor** [comment]
Thank you for your support. I edited my json file removing the <> from both IP address and Token and now everything is working fine. Happy New Year and Thank You.

{
	"bridge": {
		"name": "Homebridge",
		"username": "C8:28:3D:E9:CE:30",
		"port": 51826,
		"pin": "041-78-280"
	},

	"platforms": [{
			"platform": "SensiboSky",
			"name": "Sensibo",
			"apiKey": "cTzFrriiwg0PEQRJS0KLAfOI7Wv3UI",
			"timeLapse": 5,
			"ai": true,
			"hideFan": false,
			"hideHumidity": true,
			"fixedState": "auto"
		},
		{
			"platform": "Bond",
			"bonds": [{
				"ip_address": "192.168.1.48",
				"token": "c2b0dfeeba8034cc"
			}
		]
		}
	]
}
