### ISSUE TITLE
Add BPUP support

### ISSUE THREAD

**Issue by jqnatividad** [aarons22/homebridge-bond#62]
With the latest firmware now supporting Bond Push UDP Protocol (BPUP), it’d be nice if the plugin is updated to take advantage of it to reduce latency of updates in HomeKit.

In my case, I have a Logitech POP button going thru SmartThings to interact with Bond to control my kitchen ceiling fan/light.

It’s quite responsive, however, it takes a while for HomeKit to reflect the current state of the kitchen fan/light (about a minute).

BPUP support should minimize this latency.

Regardless, thanks for the great work!

**Comment by aarons22** [comment]
I love this idea! I just read up on BPUP and I _think_ it should be pretty straight forward to implement, but I won't really know until I dig into it.

**Comment by jdlambert** [comment]
I use BPUP a lot in my day-to-day, it's pretty stable as far as getting pushed state updates goes. Feel free to "at" me if you encounter any difficulties.

**Comment by aarons22** [comment]
@jdlambert thanks! I've used the pub/sub model in several other project so hopefully it isn't too much of a lift, but I'll be sure to reach out if I run into issues
