### ISSUE TITLE
Getting an "Invalid JSON in an platform"

### ISSUE THREAD

**Issue by OCCMakaveli23** [aarons22/homebridge-bond#63]
Followed all the instructions and no matter what I try, I cannot save...Using HOOPS. Any ideas? Thakn you!

**Comment by aarons22** [comment]
Can you post your config file?

**Comment by OCCMakaveli23** [comment]
Hi Aaron! Thank you so so much for looking into this, I sincerely
appreciate it. No matter how I add the configuration of the IP
address/token of Bond it will not allow me to save it referencing a JSON
issue.  Here is the config file:

{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYG1NH",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "xxxxx"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "A5:4D:49:01:6B:27"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "nest"
            },
            "email": "xxxxx@gmail.com",
            "password": "xxxxxxxxxxxxx",
            "googleAuth": {
                "issueToken": "xxxxxxxxxxxxx",
                "cookies": "xxxxxxxxxxxxxxx",
                "apiKey": "xxxxxxxxxxxxxxxx"
            }
        },
        {
            "platform": "Bond",
            "plugin_map": {
                "plugin_name": "homebridge-bond"
            }
        }
    ]
}

**Comment by aarons22** [comment]
Your bond platform config should look like this:
```
    {
        "platform": "Bond",
        "bonds": [
            {
                "ip_address": "<BOND_IP_ADDRESS>",
                "token": "<BOND_TOKEN>"
            }
        ],
    }
```

Where you replaced `<BOND_IP_ADDRESS>` with your IP and `<BOND_TOKEN>` with your token. You can find instructions [here](https://github.com/aarons22/homebridge-bond#configuration)

**Comment by OCCMakaveli23** [comment]
Hi Aaron - that doesn't work:

[image: image.png]

Thanks for looking into this, I really appreciate it. Any ideas?

**Comment by aarons22** [comment]
@OCCMakaveli23 can you post your updated config?

**Comment by OCCMakaveli23** [comment]
Hi Aaron - the config is exactly the same since I cannot save the new
config. I've tried different variations and cannot get anything to save the
config. It keeps referencing the JSON error. The Bond app is on version
2.10.8 and the HOOBS hub is up-to-date. Anything else you can think of?

**Comment by aarons22** [comment]
I am unfamiliar with the HOOBS hub, but unless you define the `ip_address` and `token` in your config file (similar to how you have `email` and `password` configured for Nest), it won't work.

**Comment by clean-ev** [comment]
@OCCMakaveli23 -

Finally got this running, however there are issues that I need to sort out with @aarons22 in a separate thread.

This is the config that worked for me. Note I am using Ring instead of Nest that you have.

   "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "ring"
            },
            "hideAlarmSirenSwitch": "true",
            "hideUnsupportedServices": "true",
            "refreshToken": "255LongHex"
        },
        {
            "platform": "Bond",
            "debug": true,
            "plugin_map": {
                "plugin_name": "homebridge-bond"
            },
            "bonds": [
                {
                    "ip_address": "1.1.1.1",
                    "token": "16long"
                }
            ]
        }
    ]
