### ISSUE TITLE
cachedAccessories problem when devices are removed from Bond

### ISSUE THREAD

**Issue by dxdc** [aarons22/homebridge-bond#66]
**Describe the bug**
If devices are removed from the Bond app, but were previously associated with homebridge, it causes failure on start up. This could be for a missing command or a missing device. This prevents homebridge from loading.

For example:
```
1|homebridge  | [2/24/2020, 10:43:02 AM] [Bond] Configure Accessory: Master Bedroom CF
1|homebridge  | Error: No Bond found for device Master Fan
1|homebridge  |     at BondPlatform.bondForDevice (/usr/lib/node_modules/homebridge-bond/dist/index.js:201:23)
1|homebridge  |     at BondPlatform.setupObservers (/usr/lib/node_modules/homebridge-bond/dist/index.js:143:27)
1|homebridge  |     at Timeout.setInterval [as _onTimeout] (/usr/lib/node_modules/homebridge-bond/dist/index.js:135:26)
1|homebridge  |     at ontimeout (timers.js:436:11)
1|homebridge  |     at tryOnTimeout (timers.js:300:5)
1|homebridge  |     at listOnTimeout (timers.js:263:5)
1|homebridge  |     at Timer.processTimers (timers.js:223:10)
1|homebridge  | [2/24/2020, 10:43:02 AM] Error: No Bond found for device Master Fan
1|homebridge  |     at BondPlatform.bondForDevice (/usr/lib/node_modules/homebridge-bond/dist/index.js:201:23)
1|homebridge  |     at BondPlatform.setupObservers (/usr/lib/node_modules/homebridge-bond/dist/index.js:143:27)
1|homebridge  |     at Timeout.setInterval [as _onTimeout] (/usr/lib/node_modules/homebridge-bond/dist/index.js:135:26)
1|homebridge  |     at ontimeout (timers.js:436:11)
1|homebridge  |     at tryOnTimeout (timers.js:300:5)
1|homebridge  |     at listOnTimeout (timers.js:263:5)
1|homebridge  |     at Timer.processTimers (timers.js:223:10)
```

**Expected behavior**
Graceful fallback to either/or remove devices from cachedAccessories or have it not be such an issue.

**Screenshots**

**Information (please complete the following information):**
 - Plugin version 2.5.4
 - Bond firmware version 2.10.21-beta
 - iOS version 2.20.0-beta

**Additional context**

As a temporary workaround, with the `jq` utility one can solve the issue as follows:

### To delete all bond accessories:
```sh
cd ~/.homebridge/accessories/
cat cachedAccessories | jq 'del(.[] | select(.plugin == "homebridge-bond"))' -c > cachedAccessories.new
```

### To limit the deletion of bond accessories by certain displayName keywords (note, this requires jq 1.6)

In this case, removing using the regex `/CF|Fan/`

```sh
cd ~/.homebridge/accessories/
cat cachedAccessories | jq 'del(.[] | select((.plugin == "homebridge-bond") and (.displayName|test("CF|Fan"))))' -c > cachedAccessories.new
```

After this, simply overwrite your cachedAccessories file, i.e.
```sh
mv cachedAccessories cachedAccessories.bak
mv cachedAccessories.new cachedAccessories
```

**Comment by dxdc** [comment]
This issue goes a bit deeper:

- Suppose the `reverse` option is originally added to a fan, but then deleted. HomeKit will still show this 'reverse' option until the accessory cache is purged.

> Do these values get updated for simple on/off commands like power devices when the commands are reprogrammed?

- `homebridge-bond` appears to be naming devices as `Room Name Type`. This causes very strange names, as in `Master Bedroom Master Fan Fan`. Bond doesn't allow non-unique names so this seems redundant.

**Comment by chrismerck** [comment]
On Mon, Feb 24, 2020 at 4:54 PM dxdc <notifications@github.com> wrote:

> This issue goes a bit deeper:
>
>    - Suppose the reverse option is originally added to a fan, but then
>    deleted. HomeKit will still show this 'reverse' option until the accessory
>    cache is purged.
>
>
For what it’s worth, the best way to detect a change of Features on a
device would be the change to the keys in the device/state object.

But I do see how this would require a check at every state update.

I would probably help if we had a clearer device/features object that
updates exactly when features change :)

**Comment by dxdc** [comment]
Agreed @chrismerck !

**Comment by aarons22** [comment]
@dxdc thanks for the valuable info! I don't _think_ there is a way to remove an accessory from the plugin at runtime, but I at least fixed the issue where the plugin crashes when an accessory has been removed. Can you check out [2.5.6](https://github.com/aarons22/homebridge-bond/releases/tag/2.5.6) and let me know if this has been resolved?

**Comment by dxdc** [comment]
@aarons22 thanks for making these changes! I'm not sure if it will have resolved though as by now I've long-deleted/re-added everything :)

> I don't think there is a way to remove an accessory from the plugin at runtime

I believe there is. This code does it live. I can add/remove accessories in another interface and they appear live in HomeKit. https://github.com/suderman/homebridge-isy-maker/blob/master/index.js

Something like this:
```
  // Remove this characteristic from the accessory
  var service = accessory.getService(Service[variable.serviceType]);
  var characteristic = service.getCharacteristic(Characteristic[variable.characteristicType]);
  service.removeCharacteristic(characteristic);
```

Also, `cleanupAccessoryData` is built into HAP-NodeJS and is used by other plugins (including this homebridge-ring example):

```js
                if (
                  isCamera &&
                  typeof hap.Accessory.cleanupAccessoryData === 'function'
                ) {
                  // This is a one-time cleanup that will remove persist files for old external accessories from before camera bridging in version 8
                  hap.Accessory.cleanupAccessoryData(
                    generateMacAddress(accessory.UUID)
                  )
                }
```

**Comment by aarons22** [comment]
Oh right 🤦‍♂️ well now I’ve got something else to try out 😄

**Comment by aarons22** [comment]
Converting this to a feature request since the original issue has been solved: https://github.com/aarons22/homebridge-bond/issues/76
