### ISSUE TITLE
Fan Speed Numbers vs Percentages w/Siri

### ISSUE THREAD

**Issue by twentyNoise** [aarons22/homebridge-bond#67]
I'm still using an older version because I prefer to just tell Siri to set the Fan to 1, 2, 3, 5 or 6 instead of dealing with percentages.

It would be great to be able to ask for these whole number speed changes OR percentages - or give us the option in the config.

The way I see this working is this:

1. Hey Siri set the Office Fan to 2
2. Siri Says "OK I set the Office fan to 2%"
3. The Fan object in the Home App can still show the HomeKit percentage of 33% (for a fan with 6 speeds) even though Siri says 2%.
4. This allows me to ask Siri "What is the Office fan set to?" Siri should respond with "The Fan is set to 2%" - and I'll understand that is Speed 2.

This is precisely how it works with homebridge-bond version 2.1.0

Thanks!

**Comment by iRayanKhan** [comment]
I have code somewhere that does this. I will get back to you soon. As a temporary workaround; why not use Scenes?

**Comment by twentyNoise** [comment]
Yes, version 2.1.0 does this but I think it was unintentional at first. I am still using this older version, and I'm assuming that the code is somewhere in the repository here?

Because I'm using this older version 2.1.0 and this works exactly as I have described I don't really need a workaround. But also, because of Apple's 100 scene limit I try to use Scenes as rarely as possible and I only have a few available scenes remaining.

Thanks!

**Comment by iRayanKhan** [comment]
I believe [this](https://github.com/aarons22/homebridge-bond/releases/tag/2.1.0) is the source code you are looking for.

**Comment by twentyNoise** [comment]
Yeah it would be great to be able to update the latest version and then specify an option in the Config to use this older Siri / Speed numbers.

**Comment by aarons22** [comment]
Added support for this in [2.6.0](https://github.com/aarons22/homebridge-bond/releases/tag/2.6.0)! I tested speeds 1, 2, 3 with my fan and it seems to work well, but haven't done a ton of thorough testing beyond that. Please let me know if you run into any issues!

**Comment by twentyNoise** [comment]
I just noticed that this isn't working properly anymore. That is, if you change the Config to use Speeds instead of Percentages, the Home App slider uses 1%, 2%, 3%, 4%, 5% and 6% for instance, for six speeds - which makes it difficult to use the slider to set the speeds. I believe this used to convert the speeds to percentages properly:. so Speed 3 (of 6) would be around 50%. and Speed 6 of 6 would be 100%.
