### ISSUE TITLE
Homebridge-Verification

### ISSUE THREAD

**Issue by iRayanKhan** [aarons22/homebridge-bond#68]
Hi Aaron,
Recently Oznu and the Homebridge team released [HomeBridge Verified](https://github.com/homebridge/verified). I think it would be great to have this plugin verified and add schema support for UI setup.

**Comment by aarons22** [comment]
Great idea! Probably won't be able to get to this for a bit, but happy to take any PRs related to schema support for UI setup since I haven't utilized UI setup yet.

**Comment by aarons22** [comment]
Submitted request for verification: https://github.com/homebridge/verified/issues/77

**Comment by iRayanKhan** [comment]
Thank you!
