### ISSUE TITLE
ETIMEDOUT when polling multiple devices

### ISSUE THREAD

**Issue by dxdc** [aarons22/homebridge-bond#77]
**Describe the bug**
When polling multiple Bond devices simultaneously, one of them intermittently fails with this error -- and only sometimes, but it is seems to always be this device when it does fail.

Note that my 3 blinds being polled simultaneously work fine, but the problematic one is an on/off switch is causing the problems. Note that I'm polling 4-5 devices at once.

1|homebrid | [5/24/2020, 12:12:21 AM] [Bond] A request error occurred: Error: ETIMEDOUT
1|homebrid | [5/24/2020, 12:42:21 AM] [Bond] A request error occurred: Error: ETIMEDOUT
1|homebrid | [5/24/2020, 12:56:18 AM] [Bond] A request error occurred: Error: ETIMEDOUT

(I also see this error):
[5/24/2020, 12:56:18 AM] [Bond] error getting value: TypeError: Cannot read property 'power' of undefined

**Expected behavior**
Maybe there should be some kind of queuing system to handle multiple requests, or, retry?

**Screenshots**

**Information (please complete the following information):**
 - Plugin version 2.6.0
 - Bond firmware version 2.11.10-beta

**Additional context**

**Comment by dxdc** [comment]
For now, I've updated some of the dependencies, but wondering if requestretry maybe a better option.

```json
{
  "_from": "homebridge-bond@2.6.0",
  "_id": "homebridge-bond@2.6.0",
  "_inBundle": false,
  "_integrity": "sha512-ssMfjvyPq6hEcMBQHGHDxXptU0IDR8zHFpr8a9+0MLOzqS6E1tH0YmwG8JrieytNQRhPJltEMPEnMq7uEL/YfQ==",
  "_location": "/homebridge-bond",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "homebridge-bond@2.6.0",
    "name": "homebridge-bond",
    "escapedName": "homebridge-bond",
    "rawSpec": "2.6.0",
    "saveSpec": null,
    "fetchSpec": "2.6.0"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/homebridge-bond/-/homebridge-bond-2.6.0.tgz",
  "_shasum": "027ad663790cc7d957632e00aaaaf281f4b12132",
  "_spec": "homebridge-bond@2.6.0",
  "_where": "/home/pi",
  "author": {
    "name": "Aaron Sapp"
  },
  "bugs": {
    "url": "http://github.com/aarons22/homebridge-bond/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "bluebird": "^3.7.2",
    "request": "^2.88.2",
    "request-promise": "^4.2.5"
  },
  "deprecated": false,
  "description": "A homebridge plugin to control your Bond devices over the v2 API.",
  "devDependencies": {
    "@types/request-promise": "^4.1.46",
    "prettier": "^1.18.2",
    "rimraf": "^2.6.2",
    "tslint": "^5.20.0",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "^2.9.2"
  },
  "engines": {
    "homebridge": ">=0.2.0",
    "node": ">=0.12.0"
  },
  "homepage": "https://github.com/aarons22/homebridge-bond#readme",
  "keywords": [
    "homebridge-plugin",
    "bond",
    "bond-home",
    "rf",
    "ir"
  ],
  "license": "MIT",
  "main": "dist/index.js",
  "name": "homebridge-bond",
  "repository": {
    "type": "git",
    "url": "git://github.com/aarons22/homebridge-bond.git"
  },
  "scripts": {
    "build": "tsc",
    "dev": "tsc --watch & nodemon dist",
    "format": "prettier --write \"src/**/*.ts\" \"src/**/*.js\"",
    "lint": "tslint -p tsconfig.json",
    "prepublishOnly": "npm run build"
  },
  "version": "2.6.0"
}
```

**Comment by aarons22** [comment]
I’m actually on the process of updating the dependencies and removing `request`, `request-promise` and `bluebird` in favor of `axios` and native promises (`request` has been deprecated). I haven’t seen this issue myself but i can understand how it would happen. The plugin is pretty carefree with how many requests it sends.

I’m curious is cleaning up dependencies will solve your issue.

**Comment by dxdc** [comment]
Thanks @aarons22. `axios` seems like a good option. I'm not seeing any changes (still getting an error every ~1-2 h), but may try `requestretry` next.

**Comment by dxdc** [comment]
@aarons22 just pushed a PR using a simpler approach, which is working so far. Will keep you updated on its stability.

**Comment by montanaishome** [comment]
Having same issue.  Tried updating to the new plugin released on 5/23/2020, but the devices on the bond are still failing.  The log is showing this error:

6/8/2020, 6:35:55 AM [Bond] Error getting devices: TypeError: Cannot convert undefined or null to object
6/8/2020, 6:36:00 AM [Bond] A request error occurred: Error: ETIMEDOUT
6/8/2020, 6:36:01 AM [Bond] A request error occurred: Error: ESOCKETTIMEDOUT

Relevant config.json here:

        {
            "platform": "Bond",
            "include_dimmer": false,
            "bonds": [
                {
                    "ip_address": "xxx.xxx.xxx.xxx",
                    "token": "xxxxxxxxxxxx"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-bond"
            },
            "debug": false,
            "fan_speed_values": false
        }

Any ideas?

**Comment by dxdc** [comment]
@montanaishome your issue seems unrelated. Did you double check your IP address & token?

**Comment by dxdc** [comment]
Try also the following at the command line, modifying your IP address/token and make sure you get a valid response:

```
curl -s "http://xxx.xxx.xxx.xxx/v2/devices" -X GET -d "{\"_token\": \"abcdefg\"}"
```

**Comment by aarons22** [comment]
@dxdc if 2.7.4 works, I think we can close this issue?

**Comment by dxdc** [comment]
No issues after testing so far... thanks @aarons22 ! I'll close this for now and monitor.
