### ISSUE TITLE
Error getting devices: TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by KCFT23** [aarons22/homebridge-bond#87]
I updated to 2.7.1 today and I am getting the following error when trying to load my bond device: "Error getting devices: TypeError: Cannot read property 'filter' of undefined"

I have tried the usual steps: rolling back the plugin, stopping and restarting homebridge, reinstalling the plugin, removing the device and files in "persist", etc.  I still get the same error after trying to add the device. Please let me know if you have any suggestion.

 - Plugin version 2.7.1
 - Bond firmware version 2.10.12

**Comment by KCFT23** [comment]
Some more info...
I turned on "debug" and I can see there is communication between homebridge and the bond device.  It successfully finds the device, but the error seems to happen when it is reading its properties.  My device responds with the following properties:
{"max_speed":6,"feature_light":true,"feature_brightness":true,"breeze_max_speed":6,"breeze_min_speed":1,"breeze_period":30,"_":"NNNNNNll"}  
Note: I masked the last one because I am not sure if it is sensitive.

That is when the "Error getting devices: TypeError: Cannot read property 'filter' of undefined" error happens.  Apparently it is not understanding one of those properties?

Thanks

**Comment by bnowacky** [comment]
I'm having the same results: 
- Plugin 2.7.1
- Firmware 2.10.12
- Homebridge 1.1.0

Logs: 
  `/v2/devices/1] - {"name":"ceiling fan","location":"Office","type":"CF","actions":["TurnOn","TurnOff","TogglePower","SetSpeed","IncreaseSpeed","DecreaseSpeed","TurnLightOn","TurnLightOff","ToggleLight","SetBrightness","IncreaseBrightness","DecreaseBrightness","CycleBrightness","SetTimer","BreezeOn","BreezeOff","SetBreeze"],"_":"7a5ba0fc","state":{"_":"c7c44457"},"properties":{"_":"a10fcd96"},"addr":{"_":"XXXXX"}}

[get /v2/devices/1/properties] - {"max_speed":4,"feature_light":true,"feature_brightness":true,"breeze_max_speed":3,"breeze_min_speed":1,"breeze_period":30,"_":"a10fcd96"}`

After /properties, it throws the error: 
`Error getting devices: TypeError: Cannot read property 'filter' of undefined`

**Comment by KCFT23** [comment]
ok, I though rolling back did not help.   However, when I rolled back to 2.6.0 it works fine.  So apparently it broke with 2.7.0.  I will keep using 2.6.0 until there is a fix.  Thanks

**Comment by othrside** [comment]
Same issue

**Comment by aarons22** [comment]
Sorry about that! I can't reproduce locally but attempted to fix this in 2.7.2. If that doesn't work, I will need more detailed logs with `homebridge -D` so I can see if there was something else happening around the time the error is thrown.

**Comment by patgmac** [comment]
I'm getting the same error as well, with 2.7.2. 
I'm not sure how to get the detailed logs, as "homebridge -D" seems to run an old HB config for me.

**Comment by bnowacky** [comment]
No luck on update. The results I posted previously were all that was output to logs with -D enabled in homebridge. Not a lot of additional info. 

I’m guessing it’s just trying to iterate over the array before it’s set somewhere, which is why it’s undefined,  but that’s just a guess.

**Comment by aarons22** [comment]
Thanks all - I've got a family wedding this weekend so I won't be able to look at this until sometime next week at the earliest. Please use 2.6.0 for now if you are having issues!

**Comment by aarons22** [comment]
@knavabi can you run homebridge in debug mode and post your logs? (`homebridge -D`)

**Comment by knavabi** [comment]
> @knavabi can you run homebridge in debug mode and post your logs? (`homebridge -D`)

@aarons22 Here you are:
[6/15/2020, 1:32:59 PM] [Bond] Configuring Accessory: Master Bedroom
[6/15/2020, 1:32:59 PM] TypeError: Cannot read property 'filter' of undefined
    at Object.fanSpeeds (/usr/lib/node_modules/homebridge-bond/dist/interface/Device.js:68:14)
    at BondPlatform.setupFanObservers (/usr/lib/node_modules/homebridge-bond/dist/platform.js:279:40)
    at BondPlatform.setupObservers (/usr/lib/node_modules/homebridge-bond/dist/platform.js:129:30)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-bond/dist/platform.js:112:26)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
ERROR: uncaughtException: Cannot read property 'filter' of undefined
TypeError: Cannot read property 'filter' of undefined
    at Object.fanSpeeds (/usr/lib/node_modules/homebridge-bond/dist/interface/Device.js:68:14)
    at BondPlatform.setupFanObservers (/usr/lib/node_modules/homebridge-bond/dist/platform.js:279:40)
    at BondPlatform.setupObservers (/usr/lib/node_modules/homebridge-bond/dist/platform.js:129:30)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-bond/dist/platform.js:112:26)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
INFO: INFO: Your plugin version is up-to-date
NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.4

**Comment by knavabi** [comment]
> @knavabi can you run homebridge in debug mode and post your logs? (`homebridge -D`)

It is working competently fine when downgraded to v2.6.0.

**Comment by aarons22** [comment]
Thank you this is super helpful! Seeing the files / line where it's happening makes it very easy to debug

**Comment by aarons22** [comment]
@knavabi I appreciate the logs, it was a lot easier to track down. I'm hoping 2.7.3 fixes the issue!

**Comment by bnowacky** [comment]
Just updated and looks like it's working. At least it was a simple update, and null vs. undefined is the reason Javascript is such a hated language :) 

Thanks @aarons22 ! !

**Comment by KCFT23** [comment]
thank you!  it works fine now
