### ISSUE TITLE
RFE: Option to exclude light control

### ISSUE THREAD

**Issue by sandeen** [aarons22/homebridge-bond#89]
Many fans have a light kit which is optional and may not be installed.

A config option to _not_ expose a light service for fans which have no light kit installed would be nice, to declutter the interface and remove controls for physical devices which don't exist.

**Comment by sandeen** [comment]
Never mind - I see now that if I delete the light controls in the Bond app, the plugin DTRT.  Sorry for the noise!

**Comment by chrismerck** [comment]
For what it's worth, there's also "Feature Toggles" on Smart by Bond fans (as distinct from fans connected via Bond Bridge). So, if the fan comes from the factory with a Bond chip inside and a light kit, but you decide to remove the light kit (the brands often sell cover plates), then you can select the option in the app to disable the light feature (under Device Settings > Manage Light & Dimmer). -- Similarly, you can disable Dimming or just the seperate Up/Down Light feature.

Details: http://docs-local.appbond.com/#section/Glossary/Properties

>**Feature Toggles**
>Properties starting with `feature_` are called feature toggles, and always default to true. When a feature toggle is set to false, the corresponding feature is disabled along with all dependent features, leaving only the top-level feature toggle.

>For example, on a device with Light, UpDownLight, Brightness, and UpDownLightBrightness features, setting `feature_light` to false will cause all properties, state variables, and actions for all four of these features to be removed from the API, including the feature toggles `feature_brightness` and `feature_up_down_light`. Only `feature_light` will remain.

>The intended use of feature toggles is in the Bond Home application's device settings screen, wherein the currently visible feature toggles should correspond exactly to toggle switches. Furthermore, the client need not have any feature-specific code for this: the order of feature toggles in the properties JSON object may be used as the UI display order, and the display names may be programmatically derived from the property names, e.g. `feature_up_down_light` displayed as "Up Down Light".

>Feature toggles are only available for some features, and are currently only available for Smart by Bond devices.

**Comment by chrismerck** [comment]
And,

> if I delete the light controls in the Bond app, the plugin DTRT

Indeed! When you delete the "command" the Bond API responds by not exposing the corresponding "feature" ("actions", "state", and "properties") anymore. So the plugin doesn't have to worry about the details.

Probably TMI, but there's always interesting discussions on this repo, so I cannot help myself :).
