### ISSUE TITLE
Fireplace mode

### ISSUE THREAD

**Issue by MackleMonster** [aarons22/homebridge-bond#9]
Bond added fireplace compatibility. Simple on-off commands. Is there any chance this functionality could be added to homebridge-bond? (I have no idea how to do it myself...). Thanks

**Comment by iRayanKhan** [comment]
@plainsane. I could give a shot at it. For what accessory it should show I am conflicted with a lightbulb only if you can control the flame's height. If it's just a simple on off then a switch or a plug accessory. There is a unofficial bond api which would need to be updated first .

**Comment by MackleMonster** [comment]
@iRayanKhan Hey Ryan, that would be great if you wanted to do it... It's a simple two button action, on and off, that's it. A switch would work just fine.

You're saying Bond needs to update their API first?

**Comment by plainsane** [comment]
> @plainsane. I could give a shot at it. For what accessory it should show I am conflicted with a lightbulb only if you can control the flame's height. If it's just a simple on off then a switch or a plug accessory. There is a unofficial bond api which would need to be updated first .

Yea cool, go for it, it’s going to be a couple of days.  We probably need to start breaking apart the structure, because right now, we assume fan.

**Comment by iRayanKhan** [comment]
@MackleMonster Bond it's self doesn't have an Api someone just reversed it and made it. They need to update it or I can try to reverse it. Then We can integrate it into here. I'm going to make the accessory a switch accessory. And @plainsane what if in the config for the plugin it would be:
```
{
      "platform": "Bond",
      "email": "<email>",
      "password": "<password>",
      "type":"<Fan|FirePlace,Garage>
    }
```

**Comment by Tangston311** [comment]
@iRayanKhan , just curious if there’s any update on the fireplace switch accessory - I’m looking to get a Bond to control my fireplaces and this would be perfect!

**Comment by iRayanKhan** [comment]
@Tangston311 the api hasn't been touched yet iirc if so the plugin may need a re-write based off #19

**Comment by dxdc** [comment]
@Tangston311 I have shades working, and I suspect fireplaces will be very similar. I suspect you'll just need to change the capabilities a bit so that it shows a switch and not a shade.

https://github.com/aarons22/homebridge-bond/issues/36#issuecomment-542441060

**Comment by methnen** [comment]
+1 for fireplace support.

However, I'm most interested in using it to turn OFF the fireplace and not for turning in on.

Ideally any implementation would have the option to only include an off function and no on function. The last thing I need is accidentally turning my fireplace on while I'm on vacation or something along those lines.

**Comment by ShadowBullet** [comment]
+1 for fireplace support as well, something as simple as an on/off switch would work fine for my application as that is all that mine supports

**Comment by dxdc** [comment]
Although I don't have a fireplace, something I discovered accidentally:

- Program a new device in your Bond. In the selection, choose the bottom option ("Device"). Don't choose Fireplace, etc.

- You can set a power on and/or power off command only.

- These are automatically added to Homebridge! I bought some 433 Mhz Rf-controlled outdoor electrical outlets that work perfectly under this set up.

**Comment by ethanlevine** [comment]
+1 for adding native fireplace compatibility with on/off support as a switch.

**Comment by SJNix** [comment]
Definitely another +1 for adding fireplaces!

**Comment by aarons22** [comment]
Hello! It's been a while since this issue was opened, but I just added support for the Fireplace device in [2.5.4](https://github.com/aarons22/homebridge-bond/releases/tag/2.5.4). This supports basic on / off commands via the Flame commands.

Please let me know if you run into any issues!

**Comment by andersot72** [comment]
Hello - Thanks for making this it's awesome! I just updated to 2.5.4 and restarted homebridge my fireplace doesn't show up in homebridge just my 3 fans. I did the rm -rf ~/.homebridge/accessories/cachedAccessories to remove cached accessories figured it would force an add it didn't. See log - any ideas?  Thanks in advance
[2/18/2020, 9:30:07 PM] [Bond] Getting devices...
[2/18/2020, 9:30:07 PM] [Bond] 3 devices were found on this Bond.
[2/18/2020, 9:30:07 PM] [Bond] Attempting to add 0 devices that were not previously added.
[2/18/2020, 9:30:08 PM] [Bond] Configure Accessory: Living Room CF
[2/18/2020, 9:30:08 PM] [Bond] Configure Accessory: Office CF
[2/18/2020, 9:30:08 PM] [Bond] Configure Accessory: Family Room CF

**Comment by MXNPD** [comment]
> 
> 
> Hello - Thanks for making this it's awesome! I just updated to 2.5.4 and restarted homebridge my fireplace doesn't show up in homebridge just my 3 fans. I did the rm -rf ~/.homebridge/accessories/cachedAccessories to remove cached accessories figured it would force an add it didn't. See log - any ideas? Thanks in advance
> [2/18/2020, 9:30:07 PM] [Bond] Getting devices...
> [2/18/2020, 9:30:07 PM] [Bond] 3 devices were found on this Bond.
> [2/18/2020, 9:30:07 PM] [Bond] Attempting to add 0 devices that were not previously added.
> [2/18/2020, 9:30:08 PM] [Bond] Configure Accessory: Living Room CF
> [2/18/2020, 9:30:08 PM] [Bond] Configure Accessory: Office CF
> [2/18/2020, 9:30:08 PM] [Bond] Configure Accessory: Family Room CF

Same issue here, I even removed the plugin, restarted, removed cached accessories, restarted, then re added the plugin, restarted, and it still would not see the fireplace

**Comment by aarons22** [comment]
Interesting, it should at least show up in the logs. Can one of you provide a screenshot of your Fireplace device commands in the bond app? I don't actually have a fireplace control, and just used my fan light as a fake fireplace, so it's possible I didn't replicate it correctly.

**Comment by andersot72** [comment]
Sure thing.  Here are two screenshots from the bond app. 
![IMG_56A1396B065D-1](https://user-images.githubusercontent.com/15650846/74858724-6c016d80-530b-11ea-8228-5ae61d71e066.jpeg)
![IMG_86FD3F6E4940-1](https://user-images.githubusercontent.com/15650846/74858754-758ad580-530b-11ea-80f0-93279efa7f3c.jpeg)

I also did some digging with the bond api http://docs-local.appbond.com/#section/Introduction
The odd thing is even though I can control the fireplace on and off with the bond app as shown above the fireplace doesn't show up as a listed device - the only devices that show are my fans - maybe there is something up with the Bond API.

curl -H "BOND-Token: xxxxxxxxxxxxxx" -i http://x.x.x.x/v2/devices          
HTTP/1.1 200 OK
Content-Length: 102
Content-Type: application/json; charset=utf-8

{"_":"f6d98eea","62f79939":{"_":"0ef00dea"},"66d03662":{"_":"93beb9e1"},"1df324f2":{"_":"6b7841df"}}

curl -H "BOND-Token: xxxxxxxxxxxxx" -i http://x.x.x.x/v2/devices/62f79939
HTTP/1.1 200 OK
Content-Length: 405
Content-Type: application/json; charset=utf-8

{"name":"LivingFan","type":"CF","location":"Living Room","template":"RCF84","actions":["TurnLightOn","TurnLightOff","IncreaseBrightness","SetSpeed","SetDirection","DecreaseBrightness","TurnOff","Stop","TogglePower","TurnOn","IncreaseSpeed","DecreaseSpeed","ToggleDirection","ToggleLight","SetBrightness"],"_":"0ef00dea","commands":{"_":"1d948a06"},"state":{"_":"fec38db7"},"properties":{"_":"6622fe2c"}}

curl -H "BOND-Token: xxxxxxxxxxxxxxx" -i http://x.x.x.x/v2/devices/66d03662
HTTP/1.1 200 OK
Content-Length: 320
Content-Type: application/json; charset=utf-8

{"name":"OfficeFan","type":"CF","location":"Office","template":"C2","actions":["SetSpeed","StartDimmer","TurnOff","ToggleLight","Stop","TogglePower","TurnOn","IncreaseSpeed","DecreaseSpeed","TurnLightOn","TurnLightOff"],"_":"93beb9e1","commands":{"_":"86cea7eb"},"state":{"_":"08c43156"},"properties":{"_":"54ace005"}}

curl -H "BOND-Token: xxxxxxxxxxxxx" -i http://x.x.x.x/v2/devices/1df324f2
HTTP/1.1 200 OK
Content-Length: 325
Content-Type: application/json; charset=utf-8

{"name":"FamilyFan","type":"CF","location":"Family Room","template":"C2","actions":["TurnOff","ToggleLight","SetSpeed","StartDimmer","Stop","TogglePower","TurnOn","IncreaseSpeed","DecreaseSpeed","TurnLightOn","TurnLightOff"],"_":"6b7841df","commands":{"_":"0ebdd1d6"},"state":{"_":"4f332d0f"},"properties":{"_":"405018f5"}}

Hope this helps.  Thanks

**Comment by methnen** [comment]
For what it's worth. This update worked fine for me. 

The Fireplace did show up in HomeKit as a simple switch though not as an actual fireplace.

But that's probably the best choice since HomeKit doesn't have device type for Fire Places though it DOES have one for a heater that might require some additional stuff that make it not make sense int this situation?

**Comment by methnen** [comment]
@andersot72 I've had a few cases where devices didn't show up because of Homebridge caching issues.

There's a CachedAccessories directory or file somewhere (I'm blanking on where it is) that you can delete and it'll force Homebridge to rebuild the cache on the next restart.

Not sure that's the solution for you but worth a try perhaps.

**Comment by aarons22** [comment]
@andersot72 This is super helpful! Can you try removing the fireplace and re-adding? I've seen that fix issues in the past where the device was created with the old API or get messed up in migration. Since @methnen is seeing the fireplace, I'm wondering is that is the issue...

**Comment by dxdc** [comment]
@andersot72 one thing I've seen is that if you go into `Device Settings` within the iPhone app, look for the word `Local Token`. If you don't see that, it means there was some problem as @aarons22 pointed out -- just delete, and re-add. All of my devices that are working properly all show the Local Token.

Also, for anyone who doesn't want to delete their entire cachedAccessories, see #66 where I describe a method of selectively deleting the Bond ones. (Note that homebridge should be stopped while making these adjustments).

**Comment by aarons22** [comment]
It sounds like deleting and re-adding fixes the issue. I'm closing this feature request, but any new bugs / feature improvements can be reported in a new GitHub issue

**Comment by mattob95** [comment]
Hi All - Having the same problem, have deleted, reinstalled a couple times and fireplace won't show in the Home app. I have firmware v3.8.4 on my bond, shows I have a local Token and using template RFP5 for the remote. I attempted to add a device and not using the fireplace and the commands recorded and wouldn't activate via the Bond app.

Appreciate any advice, thanks in advance.
