### ISSUE TITLE
fan direction

### ISSUE THREAD

**Issue by cirrusflyer** [aarons22/homebridge-bond#91]
I have an Homekit automation to start the ceiling fan when motion is detected in the room.  The fan is switch reversible.  Every time the automation runs, the fan will start clockwise, but I want it running counterclockwise.  I redid the automation while the fan was running counterclockwise hoping it would keep that setting, but no.  If I reverse the fan using the bond app, the next time the Homekit automation runs, it will reverse it back to clockwise.

**Comment by aarons22** [comment]
Hey @cirrusflyer - I believe I have identified the issue and fixed it in [2.8.5](https://github.com/aarons22/homebridge-bond/releases/tag/2.8.5). Let me know if you are still having issues!
