### ISSUE TITLE
Adding instructions for "Smart by BOND" devices

### ISSUE THREAD

**Issue by Silmar-99** [aarons22/homebridge-bond#94]
I was pleased to discover (after some research and trials and errors) that "Smart by BOND" devices are/may also be compatible with your plugin.

I do have a Universal Fan Remote, power by BOND for the remote part (see here: https://www.homedepot.com/p/Universal-Smart-Wi-Fi-4-Speed-Ceiling-Fan-Remote-Works-with-Google-Assistant-SmartThings-and-Alexa-99434/311264804) that I was able to integrate in HomeKit with your plugin, despite not having a BOND bridge, just the BOND App.

The setup is a little bit different, though. You will need to figure out the IP address of the module (fan). I resolved that by setting up a fixed IP using the MAC address and functionality of my router.

This token, however, will - not - be found using the command lines of the API… In order to find it, for your specific device, you need to go, in the Bond App, in the settings for that specific device you have, where will find a “Local Token”.

Use this information in the plugin setup and here you go...

**Comment by aarons22** [comment]
Thanks for this! I updated the README and the wiki for getting the IP Address with some recommendations on dealing with IP Address discovery.
