### ISSUE TITLE
Non-Stop BOND HOOBS reporting

### ISSUE THREAD

**Issue by sebastiangoldstein** [aarons22/homebridge-bond#95]
**Describe the bug**
Kind of a NOOB at HOOBS but most of my log is nonstop bond messages that look like this:

6/25/2020, 6:14:38 PM [Bond] got value: false
6/25/2020, 6:14:38 PM [Bond] got value: true
6/25/2020, 6:14:38 PM [Bond] got value: 1
6/25/2020, 6:14:38 PM [Bond] got value: true
6/25/2020, 6:14:38 PM [Bond] got value: 0
6/25/2020, 6:14:38 PM [Bond] got value: false
6/25/2020, 6:15:06 PM [Bond] got value: false
6/25/2020, 6:15:06 PM [Bond] got value: false
6/25/2020, 6:15:06 PM [Bond] got value: false
6/25/2020, 6:15:06 PM [Bond] got value: false
6/25/2020, 6:15:07 PM [Bond] got value: false
6/25/2020, 6:15:07 PM [Bond] got value: false
6/25/2020, 6:15:07 PM [Bond] got value: false
6/25/2020, 6:15:07 PM [Bond] got value: false
6/25/2020, 6:15:07 PM [Bond] got value: true
6/25/2020, 6:15:07 PM [Bond] got value: 1
6/25/2020, 6:15:07 PM [Bond] got value: true
6/25/2020, 6:15:07 PM [Bond] got value: false
6/25/2020, 6:15:07 PM [Bond] got value: 0
6/25/2020, 6:15:07 PM [Bond] got value: false
6/25/2020, 6:15:07 PM [Bond] got value: false
6/25/2020, 6:15:07 PM [Bond] got value: 0
6/25/2020, 6:15:07 PM [Bond] got value: false
6/25/2020, 6:15:07 PM [Bond] got value: false
6/25/2020, 6:15:07 PM [Bond] got value: 1
6/25/2020, 6:15:07 PM [Bond] got value: true
6/25/2020, 6:15:08 PM [Bond] got value: false
6/25/2020, 6:15:08 PM [Bond] got value: 1
6/25/2020, 6:15:08 PM [Bond] got value: true
6/25/2020, 6:15:08 PM [Bond] got value: false
6/25/2020, 6:15:08 PM [Bond] got value: 0
6/25/2020, 6:15:08 PM [Bond] got value: false
6/25/2020, 6:15:08 PM [Bond] got value: false
6/25/2020, 6:15:08 PM [Bond] got value: true
6/25/2020, 6:15:08 PM [Bond] got value: false
6/25/2020, 6:15:08 PM [Bond] got value: 0
6/25/2020, 6:15:08 PM [Bond] got value: true
6/25/2020, 6:15:08 PM [Bond] got value: 1
6/25/2020, 6:15:59 PM [Bond] got value: false
6/25/2020, 6:15:59 PM [Bond] got value: false
6/25/2020, 6:16:00 PM [Bond] got value: false
6/25/2020, 6:16:00 PM [Bond] got value: false
6/25/2020, 6:16:00 PM [Bond] got value: false
6/25/2020, 6:16:00 PM [Bond] got value: false
6/25/2020, 6:16:00 PM [Bond] got value: false
6/25/2020, 6:16:00 PM [Bond] got value: false
6/25/2020, 6:16:00 PM [Bond] got value: true
6/25/2020, 6:16:00 PM [Bond] got value: 1
6/25/2020, 6:16:00 PM [Bond] got value: true
6/25/2020, 6:16:00 PM [Bond] got value: false
6/25/2020, 6:16:00 PM [Bond] got value: 0
6/25/2020, 6:16:00 PM [Bond] got value: false
6/25/2020, 6:16:00 PM [Bond] got value: false
6/25/2020, 6:16:00 PM [Bond] got value: 0
6/25/2020, 6:16:00 PM [Bond] got value: false
6/25/2020, 6:16:01 PM [Bond] got value: false
6/25/2020, 6:16:01 PM [Bond] got value: 1
6/25/2020, 6:16:01 PM [Bond] got value: true
6/25/2020, 6:16:01 PM [Bond] got value: false
6/25/2020, 6:16:01 PM [Bond] got value: 1
6/25/2020, 6:16:01 PM [Bond] got value: true
6/25/2020, 6:16:01 PM [Bond] got value: false
6/25/2020, 6:16:01 PM [Bond] got value: 0
6/25/2020, 6:16:01 PM [Bond] got value: false
6/25/2020, 6:16:01 PM [Bond] got value: false
6/25/2020, 6:16:01 PM [Bond] got value: true
6/25/2020, 6:16:01 PM [Bond] got value: 1
6/25/2020, 6:16:01 PM [Bond] got value: true
6/25/2020, 6:16:01 PM [Bond] got value: false
6/25/2020, 6:16:01 PM [Bond] got value: 0
6/25/2020, 6:16:04 PM [Bond] got value: false
6/25/2020, 6:16:04 PM [Bond] got value: false
6/25/2020, 6:16:04 PM [Bond] got value: false
6/25/2020, 6:16:04 PM [Bond] got value: false
6/25/2020, 6:16:05 PM [Bond] got value: false
6/25/2020, 6:16:05 PM [Bond] got value: false
6/25/2020, 6:16:05 PM [Bond] got value: false
6/25/2020, 6:16:05 PM [Bond] got value: false
6/25/2020, 6:16:05 PM [Bond] got value: true
6/25/2020, 6:16:05 PM [Bond] got value: 1
6/25/2020, 6:16:05 PM [Bond] got value: true
6/25/2020, 6:16:05 PM [Bond] got value: false
6/25/2020, 6:16:05 PM [Bond] got value: 0
6/25/2020, 6:16:05 PM [Bond] got value: false
6/25/2020, 6:16:05 PM [Bond] got value: false
6/25/2020, 6:16:05 PM [Bond] got value: false
6/25/2020, 6:16:05 PM [Bond] got value: 0
6/25/2020, 6:16:06 PM [Bond] got value: false
6/25/2020, 6:16:06 PM [Bond] got value: 1
6/25/2020, 6:16:06 PM [Bond] got value: true
6/25/2020, 6:16:06 PM [Bond] got value: false
6/25/2020, 6:16:06 PM [Bond] got value: 1
6/25/2020, 6:16:06 PM [Bond] got value: true
6/25/2020, 6:16:06 PM [Bond] got value: false
6/25/2020, 6:16:06 PM [Bond] got value: 0
6/25/2020, 6:16:06 PM [Bond] got value: false
6/25/2020, 6:16:06 PM [Bond] got value: false
6/25/2020, 6:16:06 PM [Bond] got value: true
6/25/2020, 6:16:06 PM [Bond] got value: 1
6/25/2020, 6:16:06 PM [Bond] got value: true
6/25/2020, 6:16:06 PM [Bond] got value: false
6/25/2020, 6:16:06 PM [Bond] got value: 0
6/25/2020, 6:16:29 PM [Bond] got value: false
6/25/2020, 6:16:29 PM [Bond] got value: false
6/25/2020, 6:16:29 PM [Bond] got value: false
6/25/2020, 6:16:29 PM [Bond] got value: false
6/25/2020, 6:16:30 PM [Bond] got value: false
6/25/2020, 6:16:30 PM [Bond] got value: false
6/25/2020, 6:16:30 PM [Bond] got value: false
6/25/2020, 6:16:30 PM [Bond] got value: false
6/25/2020, 6:16:30 PM [Bond] got value: true
6/25/2020, 6:16:30 PM [Bond] got value: 1
6/25/2020, 6:16:30 PM [Bond] got value: true
6/25/2020, 6:16:30 PM [Bond] got value: false
6/25/2020, 6:16:30 PM [Bond] got value: 0
6/25/2020, 6:16:30 PM [Bond] got value: false
6/25/2020, 6:16:30 PM [Bond] got value: false
6/25/2020, 6:16:30 PM [Bond] got value: false
6/25/2020, 6:16:30 PM [Bond] got value: 0
6/25/2020, 6:16:31 PM [Bond] got value: false
6/25/2020, 6:16:31 PM [Bond] got value: 1
6/25/2020, 6:16:31 PM [Bond] got value: true
6/25/2020, 6:16:31 PM [Bond] got value: false
6/25/2020, 6:16:31 PM [Bond] got value: 1
6/25/2020, 6:16:31 PM [Bond] got value: true
6/25/2020, 6:16:31 PM [Bond] got value: false
6/25/2020, 6:16:31 PM [Bond] got value: 0
6/25/2020, 6:16:31 PM [Bond] got value: false
6/25/2020, 6:16:31 PM [Bond] got value: false
6/25/2020, 6:16:31 PM [Bond] got value: true
6/25/2020, 6:16:31 PM [Bond] got value: 1
6/25/2020, 6:16:31 PM [Bond] got value: true
6/25/2020, 6:16:31 PM [Bond] got value: false
6/25/2020, 6:16:31 PM [Bond] got value: 0

**Expected behavior**
Is this reporting normal?
How do I stop it?
Should it happen less frequently?
All of my BOND controls appear to work in the Apple Home App. 

**Information (please complete the following information):**
 - Plugin version 2.7.4 published 6/18/2020 • 6 days ago
 - Bond firmware version: v2.12.2-beta
 - iOS version 13.6

**Comment by aarons22** [comment]
This was noted here: https://github.com/aarons22/homebridge-bond/issues/93

It’ll be fixed in the next release!
