### ISSUE TITLE
Having trouble with light toggle no longer functioning...

### ISSUE THREAD

**Issue by methnen** [aarons22/homebridge-bond#96]
For the last several days I've been unable to get the light toggle to work anymore.

The light toggle works via the Bond app fine but when I do it via the Homebridge Accessories panel or in HomeKit nothing happens.

I can't say for certain that this happened after updating Homebridge to the latest but I think it coincides with it.

Homebridge version:
Version 1.1.1

Plugin version (homebridge-bond):
v2.7.4

Node.js Version:
 v12.18.1

NPM Version
v6.14.5

Bond Firmware Version:
v2.10.21

And here's what my config looks like:
```
       {
            "bonds": [
                {
                    "ip_address": "192.168.0.XXXX",
                    "token": "XXXXXXXXXX"
                }
            ],
            "include_dimmer": false,
            "fan_speed_values": true,
            "platform": "Bond"
        },
```

Should note that the fan speed control seems fine.

Anyone have any similar issue or ideas?

**Comment by methnen** [comment]
Alright, I believe I found the issue though I'm unsure how to resolve it now.

I uninstalled the plugin and reinstalled it and this time it created Fan Up Light and Fan Down Light buttons. My fan does not have an Up Light and when clicking that one nothing happens. I'm guessing something got crossed in the wires and with my previous setup of the plugin that light toggle was trying to switch the non existent Up Light.

When clicking the Down Light button the light toggles as expected.

A possibly simple fix would be to provide a way to simply hide the Up Light toggle from HomeKit. 

Is that a possibility in some way that I'm not seeing?

If this Up light toggle is coming from the Bond hub itself than that's another issue possibly as I never told the Bond that my fan had an Up Light and in the Bond app I still only see a Down Light.

Thoughts/Ideas?

**Comment by aarons22** [comment]
Hey @methnen! Sorry for the delay on this. The bond hub tells the plugin that there is an up / down light, so I would make sure your bond doesn't think that is the case. If it looks good on the app, I would recommend [clearing cached accessories](https://github.com/aarons22/homebridge-bond/wiki/Clearing-Cached-Accessories) and trying again.

If that doesn't work, please run your homebridge in[ debug mode](https://github.com/aarons22/homebridge-bond/wiki/Enabling-Debug-Mode) and post your logs here!

**Comment by methnen** [comment]
So super late reply on my end too, but yes, I had to delete the fan from Bond and re-add it back in manually. I'd previously used the automatic device detection and it for some reason sets it up incorrectly as a fan with a top and bottom light.

The cleared cached accessories and restarted Homebridge and it's now working correctly again.

**Comment by aarons22** [comment]
Awesome, thanks for the reply!
